# Copyright (c) 2026, Dr.Anmar Project Developers.
# SPDX-License-Identifier: BSD-3-Clause

"""Clinician-facing composed operating-room presets for Dr.Anmar."""

from __future__ import annotations

from typing import Any


CT_MULTI_ORGAN = "OR_scene_CTLiver-Prostate-Bladder"
MAISI_LIVER_27 = "OR_scene_MAISI_imagesTr_liver_27_relabel_resample1_syn_seed6_postprocess"
MAISI_S0253 = "OR_scene_MAISI_s0253_ct_relabel_resample1_syn_seed6_postprocess"
MAISI_S0702 = "OR_scene_MAISI_s0702_ct_relabel_resample2_syn_seed6_postprocess"
MAISI_S0994 = "OR_scene_MAISI_s0994_ct_relabel_resample2_syn_seed6_postprocess"
MAISI_S1269 = "OR_scene_MAISI_s1269_ct_relabel_resample1_syn_seed6_postprocess"
SURGICAL_S1371 = "OR_scene_s1371"


def step(step_id: str, title: str, instruction: str, signal: str) -> dict[str, str]:
    return {"id": step_id, "title": title, "instruction": instruction, "signal": signal}


PROCEDURE_ROOMS: tuple[dict[str, Any], ...] = (
    {
        "id": "needle-pickup",
        "title": "Needle pickup",
        "category": "Needle skills",
        "difficulty": "Foundation",
        "task": "Isaac-Lift-Needle-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "CT liver field",
        "robot": "dVRK PSM",
        "instrument": "Large needle driver",
        "objective": "Approach the curved needle, grasp its body, lift it clear of the tray, and hold it stably.",
        "interaction": "Rigid curved needle with physical contact, grasp and lift.",
        "fidelity": "nvidia_i4h_reference",
        "source_workflow": "robotic_surgery/lift_needle_organs",
        "show_waypoint_markers": False,
        "guide_kind": "pickup",
        "proxy_organ": None,
        "steps": [
            step("approach", "Approach", "Bring the open jaws toward the middle third of the curved needle.", "tool motion"),
            step("grasp", "Grasp", "Close the gripper around the needle body; Space toggles the jaws.", "gripper close"),
            step("lift", "Lift", "Raise the grasped needle above its starting plane.", "needle elevation"),
            step("orient", "Orient", "Rotate the needle into a controlled, readable presentation.", "tool orientation"),
            step("recover", "Recover", "Hold the final pose without dropping the needle.", "stable hold"),
        ],
        "truth_note": "Foundation room: rigid needle handling without thread or tissue interaction.",
    },
    {
        "id": "needle-transfer",
        "title": "Needle handover",
        "category": "Needle skills",
        "difficulty": "Intermediate",
        "task": "Isaac-Handover-Needle-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "CT liver field",
        "robot": "Dual dVRK PSM",
        "instrument": "Two needle drivers",
        "objective": "Pick up the curved needle, present it to the second instrument, transfer the grasp, and separate safely.",
        "interaction": "Native ORBIT-Surgical dual-arm needle rigid-body physics.",
        "fidelity": "native_object_physics",
        "guide_kind": "handover",
        "proxy_organ": None,
        "steps": [
            step("pickup", "Pick up", "Instrument 1 secures the middle third of the needle.", "first grasp"),
            step("present", "Present", "Move the needle into a stable shared workspace.", "object movement"),
            step("receive", "Receive", "Instrument 2 closes on the exposed needle body.", "second grasp"),
            step("release", "Release", "Instrument 1 opens only after the receiving grasp is stable.", "gripper exchange"),
            step("separate", "Separate", "Move both tools apart while retaining the needle.", "stable recovery"),
        ],
        "truth_note": "The transfer uses the upstream dual-PSM needle environment; success scoring remains a research measure.",
    },
    {
        "id": "suture-threading-path",
        "title": "Single interrupted stitch",
        "category": "Needle skills",
        "difficulty": "Intermediate",
        "task": "Isaac-Handover-Needle-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Liver surface",
        "robot": "Dual dVRK PSM",
        "instrument": "Two needle drivers",
        "objective": "Drive the curved needle through tissue, pull the attached suture through the entry and exit, close the loop, and cinch it before recovery.",
        "interaction": "Physical needle manipulation with a constrained suture strand, material-coordinate entry and exit anchors, surface friction, live tissue approximation, and a persistent cinch constraint.",
        "fidelity": "interactive_suture_mechanics",
        "guide_kind": "threading",
        "proxy_organ": None,
        "steps": [
            step("pickup", "Pick up", "Secure the needle away from its tip.", "gripper close"),
            step("entry", "Align entry", "Place the needle tip inside the cyan entry target.", "waypoint 1"),
            step("arc", "Pass through", "Rotate through the amber middle target and pull thread through the tissue.", "thread tension"),
            step("exit", "Exit tissue", "Bring the needle tip out through the green exit target.", "exit anchor"),
            step("knot", "Close and cinch", "Return the needle around the entry and pull until the loop cinches.", "knot constraint"),
            step("recover", "Recover", "Move the needle clear while preserving the tightened suture.", "stable hold"),
        ],
        "truth_note": "The strand, surface-bound entry/exit anchors, puncture dimples, slack, strain, tension, frictional slip, tissue approximation, pullout, tearing, breakage and knot retention run live and are recorded. Parameters are unvalidated research defaults, not validated suture material or human-tissue biomechanics.",
    },
    {
        "id": "liver-cutting-path",
        "title": "Liver incision practice",
        "category": "Dissection planning",
        "difficulty": "Intermediate",
        "task": "Isaac-Reach-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Liver",
        "robot": "dVRK PSM",
        "instrument": "PSM training tool",
        "objective": "Open a continuous incision through the liver surface mesh while keeping the tool inside the ordered safety corridor.",
        "interaction": "The swept tool removes intersected OpenUSD mesh faces, exposes an incision bed, updates topology live, and records cut length and topology revisions.",
        "fidelity": "topology_changing_cut",
        "guide_kind": "cutting_path",
        "proxy_organ": None,
        "steps": [
            step("plan", "Inspect", "Identify the cyan start and the complete amber corridor before moving.", "camera review"),
            step("approach", "Approach", "Move above the start target and settle the tool orientation.", "waypoint 1"),
            step("trace", "Cut", "Keep the tool on the tissue and open a continuous incision along every corridor target.", "topology change"),
            step("finish", "Finish", "Reach the green endpoint and inspect the opened mesh edges.", "cut endpoint"),
            step("recover", "Recover", "Lift away from the planned incision corridor.", "tool clearance"),
        ],
        "truth_note": "The OpenUSD liver removes and opens swept faces, deforms around the incision, records cut resistance/work, and restores exactly on reset. It is a reduced-order research model, not validated fracture, bleeding, cautery or human-tissue force behavior.",
    },
    {
        "id": "liver-retraction",
        "title": "Liver retraction practice",
        "category": "Tissue handling",
        "difficulty": "Intermediate",
        "task": "Isaac-Lift-Block-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Liver",
        "robot": "dVRK PSM",
        "instrument": "Atraumatic grasper control",
        "objective": "Grasp the liver-shaped training target, lift it into a retracted position, and maintain a stable exposure.",
        "interaction": "Native grasp dynamics move the organ while the visible OpenUSD surface deforms around the grasp, limits displacement, and elastically recovers after release.",
        "fidelity": "deformable_surface_hybrid",
        "guide_kind": "retraction",
        "proxy_organ": "Liver_topo_blender",
        "steps": [
            step("inspect", "Inspect", "Choose a broad, accessible grasp region on the target.", "camera review"),
            step("approach", "Approach", "Bring the open jaws to the retraction target.", "tool motion"),
            step("grasp", "Grasp", "Close and confirm the target follows the tool.", "object coupling"),
            step("retract", "Retract", "Lift and move the target to expose the working area.", "object displacement"),
            step("hold", "Hold", "Maintain stable exposure before release.", "stable hold"),
        ],
        "truth_note": "The official liver surface now couples deformation over its mesh, approximately preserves volume, resists at an attachment region and elastically recovers while native rigid dynamics provide gross motion. Its material profile remains unvalidated research data.",
    },
    {
        "id": "gallbladder-reposition",
        "title": "Gallbladder repositioning",
        "category": "Tissue handling",
        "difficulty": "Intermediate",
        "task": "Isaac-Lift-Block-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Gallbladder",
        "robot": "dVRK PSM",
        "instrument": "Atraumatic grasper control",
        "objective": "Pick up the gallbladder-shaped target, reposition it to the indicated workspace, and release deliberately.",
        "interaction": "Native grasp dynamics with localized compliant deformation and elastic recovery of the official OpenUSD gallbladder surface.",
        "fidelity": "deformable_surface_hybrid",
        "guide_kind": "reposition",
        "proxy_organ": "Gallbladder_topo_blender",
        "steps": [
            step("approach", "Approach", "Move to the broad body of the target with the gripper open.", "tool motion"),
            step("grasp", "Grasp", "Close gently and confirm target motion.", "object coupling"),
            step("lift", "Lift", "Clear the starting surface before translating.", "object elevation"),
            step("place", "Place", "Move into the green placement region and open the jaws.", "target displacement"),
            step("recover", "Recover", "Withdraw without disturbing the placed target.", "tool clearance"),
        ],
        "truth_note": "The official gallbladder surface uses mesh-coupled deformation, approximate volume preservation, attachment resistance and elastic recovery while a rigid core supplies stable gross motion. Its material profile awaits bench calibration.",
    },
    {
        "id": "bladder-handover",
        "title": "Bladder-part bimanual relocation",
        "category": "Tissue handling",
        "difficulty": "Advanced",
        "task": "Isaac-Handover-Block-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Bladder",
        "robot": "Dual dVRK PSM",
        "instrument": "Two atraumatic grasper controls",
        "objective": "Move a bladder-shaped training target between instruments and place it in a new operative position.",
        "interaction": "Dual-arm handover with a locally deforming OpenUSD bladder surface, bounded strain, elastic recovery, and native gross-body grasp dynamics.",
        "fidelity": "deformable_surface_hybrid",
        "guide_kind": "handover",
        "proxy_organ": "Bladder_topo_blender",
        "steps": [
            step("pickup", "Pick up", "Instrument 1 lifts the target clear of the table.", "first grasp"),
            step("present", "Present", "Stabilize the target in the shared workspace.", "object motion"),
            step("receive", "Receive", "Instrument 2 grasps before Instrument 1 releases.", "second grasp"),
            step("place", "Relocate", "Move the retained target to its indicated new position.", "object displacement"),
            step("recover", "Recover", "Release and separate both instruments.", "stable release"),
        ],
        "truth_note": "The bladder surface responds through coupled strain, approximate volume preservation, attachment resistance and recovery while the upstream task supplies gross-body dynamics. The research-default bladder profile is not clinically validated.",
    },
    {
        "id": "synthetic-anatomy-navigation",
        "title": "Anatomy-variation navigation",
        "category": "Visual robustness",
        "difficulty": "Research challenge",
        "task": "Isaac-Reach-PSM-IK-Rel-v0",
        "anatomy_scene": SURGICAL_S1371,
        "anatomy_focus": "Multi-organ surgical anatomy",
        "robot": "dVRK PSM",
        "instrument": "PSM training tool",
        "objective": "Navigate an ordered target path in a distinct patient-anatomy geometry and record a comparable trajectory.",
        "interaction": "Official OpenUSD anatomy variation with native relative-IK tool control and 3D waypoint scoring.",
        "fidelity": "anatomy_context",
        "guide_kind": "navigation",
        "proxy_organ": None,
        "steps": [
            step("survey", "Survey", "Use the endoscope to identify anatomy and all visible targets.", "camera review"),
            step("approach", "Approach", "Move to the first cyan target.", "waypoint 1"),
            step("navigate", "Navigate", "Visit each amber target in order.", "ordered waypoints"),
            step("finish", "Finish", "Reach the green endpoint.", "final waypoint"),
            step("recover", "Recover", "Return to a safe observation pose.", "tool clearance"),
        ],
        "truth_note": "This scene evaluates navigation across anatomy variation; it is not a clinical procedure model.",
    },
)


# These rooms deliberately reuse a small set of native ORBIT-Surgical tasks.
# The native task supplies the robot and stable contact loop; Dr.Anmar composes
# procedure-specific OpenUSD geometry, guidance, mutable tissue and telemetry on
# top.  This keeps every room recordable with the same observation/action schema.
ADVANCED_PROCEDURE_ROOMS: tuple[dict[str, Any], ...] = (
    {
        "id": "vascular-shunt-insertion",
        "title": "Vascular shunt insertion",
        "category": "Access and device placement",
        "difficulty": "Intermediate",
        "task": "Isaac-Lift-Block-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Liver vascular field",
        "robot": "dVRK PSM",
        "instrument": "Atraumatic grasper",
        "objective": "Acquire a flexible shunt, align its tip with the vessel lumen, advance without wall overload, and verify stable placement and patency.",
        "interaction": "Interactive flexible-tube insertion with lumen alignment, insertion depth, buckling, wall-load and patency telemetry.",
        "fidelity": "interactive_tube_insertion",
        "guide_kind": "tube_insertion",
        "proxy_organ": None,
        "waypoints": ((-0.058, -0.025, 0.060), (-0.034, -0.012, 0.052), (-0.008, 0.002, 0.047), (0.024, 0.018, 0.044)),
        "steps": [
            step("acquire", "Acquire shunt", "Close on the reinforced middle of the flexible shunt.", "secure grasp"),
            step("align", "Align lumen", "Bring the shunt tip coaxially to the cyan vessel opening.", "radial and angular error"),
            step("insert", "Advance", "Advance along the vessel axis while watching wall load and buckling.", "insertion depth"),
            step("seat", "Seat", "Reach the planned depth without exceeding the wall-load advisory band.", "target depth"),
            step("verify", "Verify patency", "Stop motion and confirm placement, low wall load and simulated flow.", "patency proxy"),
        ],
        "success_metrics": ["insertion depth", "radial error", "wall-load proxy", "buckling events", "patency proxy"],
        "truth_note": "This room makes the ORBIT-style tube-in-vessel shunt benchmark runnable. Flexible geometry, wall load and patency are deterministic engineering models; they are not a clinically calibrated vessel, flow or implant model.",
    },
    {
        "id": "running-suture",
        "title": "Running suturing",
        "category": "Suturing",
        "difficulty": "Advanced",
        "task": "Isaac-Handover-Needle-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Liver wound edge",
        "robot": "Dual dVRK PSM",
        "instrument": "Two needle drivers",
        "objective": "Place a continuous row of tissue bites with consistent spacing and tension, then secure the final loop.",
        "interaction": "Multi-bite constrained suture with persistent thread, repeated tissue anchors, spacing, tension, closure-gap and cinch telemetry.",
        "fidelity": "interactive_suture_mechanics",
        "guide_kind": "running_suture",
        "proxy_organ": None,
        "target_anchors": 6,
        "target_stitches": 3,
        "waypoints": ((-0.050, -0.026, 0.030), (-0.031, -0.012, 0.039), (-0.010, 0.000, 0.044), (0.011, 0.011, 0.041), (0.032, 0.021, 0.035), (0.050, 0.030, 0.031)),
        "steps": [
            step("first_bite", "First bite", "Drive the first controlled entry and exit across the wound.", "anchors 1-2"),
            step("second_bite", "Second bite", "Advance along the wound with similar bite width and depth.", "anchors 3-4"),
            step("third_bite", "Third bite", "Complete the final planned bite without crossing the thread.", "anchors 5-6"),
            step("tension", "Balance tension", "Pull until the wound edges approximate without over-tightening.", "closure gap"),
            step("secure", "Secure", "Cinch the terminal loop and recover with stable thread tension.", "knot constraint"),
        ],
        "success_metrics": ["stitch count", "bite spacing", "closure gap", "peak tension", "over-tension events"],
        "truth_note": "Thread slack/strain, anchors, pullout, breakage, surface response, knot security and closure scoring run live. Tissue holding strength, ischemia and material parameters remain research defaults pending bench and clinician calibration.",
    },
    {
        "id": "intracorporeal-knot",
        "title": "Intracorporeal knot tying",
        "category": "Suturing",
        "difficulty": "Advanced",
        "task": "Isaac-Handover-Needle-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Liver wound edge",
        "robot": "Dual dVRK PSM",
        "instrument": "Two needle drivers",
        "objective": "Form opposing throws, seat a square knot, and tighten it without tissue strangulation or loop slippage.",
        "interaction": "Two-arm loop routing with crossing direction, throw count, symmetry, knot tightness, slippage and tension telemetry.",
        "fidelity": "interactive_suture_mechanics",
        "guide_kind": "knot_tying",
        "proxy_organ": None,
        "target_anchors": 2,
        "target_throws": 3,
        "waypoints": ((-0.035, -0.020, 0.043), (-0.012, 0.008, 0.052), (0.018, -0.005, 0.049), (-0.012, -0.023, 0.043), (0.024, 0.015, 0.040)),
        "steps": [
            step("loop", "Form loop", "Cross the working strand around the opposing instrument.", "loop crossing"),
            step("throw_one", "First throw", "Pull the first throw down evenly toward the tissue.", "throw 1"),
            step("reverse", "Reverse direction", "Create the opposing crossing required for a square knot.", "crossing direction"),
            step("throw_two", "Second throw", "Seat the opposing throw without loosening the first.", "throw 2"),
            step("secure", "Secure and inspect", "Complete the final throw and inspect tension and slippage.", "knot security"),
        ],
        "success_metrics": ["throw count", "alternating crossings", "knot tightness", "slippage proxy", "peak tension"],
        "truth_note": "The rendered loop and knot constraints are interactive. Knot topology and tension are suitable for algorithm development, not validated clinical knot-security certification.",
    },
    {
        "id": "needle-hoop-threading",
        "title": "Threaded needle ring pass and surgeon's knot",
        "category": "Needle skills",
        "difficulty": "Intermediate",
        "task": "Isaac-Handover-Needle-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Dry-lab training field",
        "robot": "Dual dVRK PSM",
        "instrument": "Two needle drivers",
        "objective": "Pick up the threaded needle, rotate its sharp tip through the physical ring, complete a true bimanual handoff, then form and seat a proper 2-1-1 surgeon's knot.",
        "interaction": "Rigid OpenUSD hoop and stand, live position-based strand, needle-tip crossing telemetry, bimanual wrap recognition, throw-direction checks, seating symmetry, tension and slippage feedback.",
        "fidelity": "native_needle_rigid_hoop_plus_bimanual_knot_training",
        "implementation_origin": "dr_anmar_nvidia_stack_extension",
        "platform_foundation": "NVIDIA Isaac Sim 5.1, Isaac Lab, PhysX and OpenUSD",
        "nvidia_reference_tasks": ["robotic_surgery/lift_needle", "robotic_surgery/reach_dual_psm"],
        "validation_status": "research_extension_pending_bench_validation",
        "guide_kind": "hoop_threading",
        "proxy_organ": None,
        "hide_anatomy": True,
        "show_waypoint_markers": False,
        "hoop_inner_radius_m": 0.017,
        "hoop_tube_radius_m": 0.0025,
        "target_throws": 3,
        "waypoints": ((-0.045, 0.000, 0.065), (0.000, 0.000, 0.065), (0.045, 0.000, 0.065)),
        "steps": [
            step("pickup", "Pick up the threaded needle", "Close on the middle third of the needle and confirm that the suture follows continuously from its eye.", "needle and suture custody"),
            step("pass", "Pass the hoop", "Center the sharp tip, follow the needle curvature through the opening, and clear the ring without contact.", "clean plane crossing"),
            step("tail", "Control both ends", "Use Instrument 2 to secure the free tail and bring both strand ends into the knot field.", "bimanual tail control"),
            step("double", "Double first throw", "Wrap twice in one direction, capture the tail, and pull both ends apart evenly to seat the first throw.", "two wraps"),
            step("oppose", "Opposing single throw", "Reverse the crossing direction, make one wrap, then seat it without loosening the first throw.", "direction reversal"),
            step("secure", "Final securing throw", "Return to the original crossing direction, make one final wrap, and draw both ends down symmetrically.", "2-1-1 sequence"),
            step("inspect", "Inspect and recover", "Confirm the knot is compact, the ends are balanced, tension is controlled, and the seated knot does not slip.", "security and slippage"),
        ],
        "success_metrics": ["clean hoop pass", "2-1-1 wrap sequence", "opposing throw direction", "seating symmetry", "strand tension", "slippage"],
        "truth_note": "The hoop, needle and strand are interactive simulator geometry. Knot recognition and security are deterministic dry-lab engineering proxies for education and algorithm development, not clinical proficiency certification.",
    },
    {
        "id": "needle-passing-regrasp",
        "title": "Needle passing and regrasping",
        "category": "Needle skills",
        "difficulty": "Intermediate",
        "task": "Isaac-Handover-Needle-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Liver operative field",
        "robot": "Dual dVRK PSM",
        "instrument": "Two needle drivers",
        "objective": "Pass the needle through an ordered spatial target, regrasp on its body, and present a usable needle orientation for the next stitch.",
        "interaction": "Native dual-arm needle grasping plus ordered 3D pass targets, receiver approach, stable exchange and recovery scoring.",
        "fidelity": "native_object_physics",
        "guide_kind": "needle_pass",
        "proxy_organ": None,
        "waypoints": ((-0.040, -0.028, 0.050), (-0.014, -0.006, 0.062), (0.012, 0.012, 0.061), (0.040, 0.026, 0.050)),
        "steps": [
            step("orient", "Orient needle", "Rotate the needle into a readable presentation.", "needle pose"),
            step("pass", "Pass target", "Move the needle body through the highlighted spatial target.", "ordered waypoint"),
            step("receive", "Receive", "Close Instrument 2 on a safe section of the exposed needle body.", "second grasp"),
            step("release", "Release", "Open Instrument 1 after the receiving grasp is stable.", "handover"),
            step("present", "Present", "Recover with the needle ready for the next tissue bite.", "final pose"),
        ],
        "success_metrics": ["target passage", "dual-grasp overlap", "drop events", "final presentation", "motion economy"],
        "truth_note": "Needle and robot contact use native simulator physics. Usable-grasp and presentation scores are research measures awaiting clinician thresholds.",
    },
    {
        "id": "anastomosis-leak-test",
        "title": "Anastomosis and leak test",
        "category": "Reconstruction",
        "difficulty": "Research challenge",
        "task": "Isaac-Handover-Needle-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Bowel-style lumen phantom",
        "robot": "Dual dVRK PSM",
        "instrument": "Two needle drivers",
        "objective": "Approximate two lumen ends with distributed stitches, secure the closure, and perform a simulated pressure leak test.",
        "interaction": "Two-ring lumen phantom, multi-bite thread anchors, closure-gap, constriction, pressure and leak-rate telemetry.",
        "fidelity": "interactive_anastomosis_proxy",
        "guide_kind": "anastomosis",
        "proxy_organ": None,
        "target_anchors": 8,
        "target_stitches": 4,
        "waypoints": ((-0.042, -0.026, 0.038), (-0.025, -0.006, 0.048), (-0.006, 0.014, 0.046), (0.014, 0.020, 0.041), (0.032, 0.004, 0.045), (0.015, -0.016, 0.048), (-0.010, -0.022, 0.043), (-0.035, -0.012, 0.039)),
        "steps": [
            step("align", "Align lumens", "Bring the two lumen ends together without twisting them.", "ring alignment"),
            step("posterior", "Posterior wall", "Place evenly distributed posterior bites.", "stitches 1-2"),
            step("anterior", "Anterior wall", "Complete the anterior closure while preserving lumen diameter.", "stitches 3-4"),
            step("secure", "Secure closure", "Tie and balance tension around the circumference.", "knot and constriction"),
            step("test", "Pressure test", "Hold still while the simulated lumen is pressurized and leakage is measured.", "leak rate"),
        ],
        "success_metrics": ["stitch distribution", "closure gap", "lumen narrowing", "leak-rate proxy", "peak tension"],
        "truth_note": "The lumen, pressure and leakage model is an interactive research proxy. It does not reproduce validated bowel or vascular biomechanics, perfusion or clinical leak testing.",
    },
    {
        "id": "vessel-clip-divide",
        "title": "Clip, ligate and divide",
        "category": "Vascular control",
        "difficulty": "Advanced",
        "task": "Isaac-Reach-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Gallbladder vascular field",
        "robot": "Dual dVRK PSM",
        "instrument": "Clip applier and scissors controls",
        "objective": "Expose a target vessel, place two secure clips with spacing, and divide only inside the protected interval.",
        "interaction": "Interactive vessel centerline with clip placement, spacing, protected-zone, division and residual-flow telemetry.",
        "fidelity": "interactive_vascular_proxy",
        "guide_kind": "clip_divide",
        "proxy_organ": None,
        "waypoints": ((-0.045, -0.024, 0.045), (-0.020, -0.008, 0.043), (0.004, 0.004, 0.042), (0.025, 0.015, 0.041), (0.047, 0.025, 0.045)),
        "steps": [
            step("expose", "Expose vessel", "Use the second instrument to maintain a stable view.", "exposure"),
            step("clip_one", "Place proximal clip", "Seat the first clip squarely across the target vessel.", "clip 1"),
            step("clip_two", "Place distal clip", "Place a second clip with a safe division interval.", "clip 2"),
            step("divide", "Divide", "Cut only between the two confirmed clips.", "protected division"),
            step("inspect", "Inspect", "Confirm retained clips and simulated flow arrest.", "residual flow"),
        ],
        "success_metrics": ["clip count", "clip spacing", "division location", "protected contacts", "residual-flow proxy"],
        "truth_note": "Clips, retention, compression, over-compression damage, division, residual flow and rebleed are interactive research proxies. Energy spread, vessel burst pressure and device-specific deployment are not clinically calibrated.",
    },
    {
        "id": "bleeding-control",
        "title": "Bleeding control and hemostasis",
        "category": "Complication management",
        "difficulty": "Research challenge",
        "task": "Isaac-Reach-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Liver vascular field",
        "robot": "Dual dVRK PSM",
        "instrument": "Grasper, suction and clip controls",
        "objective": "Maintain exposure, localize the bleeding source, reduce visual contamination, and achieve stable simulated hemostasis.",
        "interaction": "Dynamic bleed source with distance-based suction, compression, clip effect, visibility and rebleed telemetry.",
        "fidelity": "interactive_hemostasis_proxy",
        "guide_kind": "hemostasis",
        "proxy_organ": None,
        "waypoints": ((-0.040, -0.026, 0.060), (-0.018, -0.009, 0.048), (0.005, 0.004, 0.041), (0.026, 0.015, 0.046)),
        "steps": [
            step("expose", "Maintain exposure", "Keep the source visible while bringing suction into the field.", "visibility"),
            step("localize", "Localize source", "Center the instrument on the bleeding origin.", "source distance"),
            step("control", "Temporary control", "Apply compression or suction to reduce the active flow.", "bleed rate"),
            step("definitive", "Definitive control", "Place the indicated clip or maintain the planned control action.", "flow arrest"),
            step("observe", "Observe for rebleed", "Hold the field stable and confirm the source remains controlled.", "rebleed test"),
        ],
        "success_metrics": ["time to localization", "blood-loss proxy", "minimum visibility", "time to control", "rebleed"],
        "truth_note": "Bleeding, suction, compression force, accumulated vessel damage, definitive control and rebleed are coupled deterministic telemetry models. They are not a validated fluid, coagulation or energy-device simulation.",
    },
    {
        "id": "tissue-plane-dissection",
        "title": "Tissue-plane dissection",
        "category": "Dissection",
        "difficulty": "Advanced",
        "task": "Isaac-Reach-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Gallbladder and liver plane",
        "robot": "Dual dVRK PSM",
        "instrument": "Grasper and dissector controls",
        "objective": "Create exposure and separate the highlighted tissue plane while preserving the protected duct and vessel corridors.",
        "interaction": "Topology-changing separation along an OpenUSD tissue plane with traction, plane deviation and protected-structure contact telemetry.",
        "fidelity": "topology_changing_dissection",
        "guide_kind": "dissection",
        "proxy_organ": None,
        "waypoints": ((-0.052, -0.025, 0.047), (-0.030, -0.012, 0.044), (-0.006, 0.000, 0.042), (0.019, 0.012, 0.043), (0.045, 0.024, 0.049)),
        "steps": [
            step("expose", "Create traction", "Use the second instrument to open the intended plane.", "bimanual exposure"),
            step("enter", "Enter plane", "Start at the cyan low-risk edge.", "plane entry"),
            step("separate", "Separate", "Advance through the amber tissue plane with short controlled motions.", "topology separation"),
            step("protect", "Protect structures", "Stay outside the marked duct and vessel corridors.", "protected clearance"),
            step("inspect", "Inspect plane", "Stop and inspect the completed separation before recovery.", "plane completion"),
        ],
        "success_metrics": ["plane progress", "off-plane distance", "protected contacts", "traction stability", "surface injury"],
        "truth_note": "The OpenUSD surface changes topology along the selected plane. Connective-tissue fracture, thermal injury and anatomy-specific critical-view criteria require dedicated calibration and clinician validation.",
    },
    {
        "id": "ultrasound-guided-access",
        "title": "Ultrasound-guided needle access",
        "category": "Image-guided intervention",
        "difficulty": "Advanced",
        "task": "Isaac-Reach-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": MAISI_S0253,
        "anatomy_focus": "Synthetic abdominal target",
        "robot": "Dual dVRK PSM",
        "instrument": "Instrument 1 ultrasound probe · Instrument 2 access needle",
        "objective": "Acquire a simulated ultrasound target, plan an in-plane trajectory, and advance to the target while avoiding the protected vessel.",
        "interaction": "Live procedural B-mode rehearsal with probe-to-target confidence, needle visibility, target error and protected-structure telemetry.",
        "fidelity": "procedural_ultrasound_proxy",
        "guide_kind": "ultrasound_access",
        "proxy_organ": None,
        "waypoints": ((-0.050, -0.030, 0.075), (-0.026, -0.013, 0.058), (-0.004, 0.003, 0.047), (0.018, 0.017, 0.037)),
        "steps": [
            step("survey", "Survey", "Move the probe until the target is centered and confidence is stable.", "target confidence"),
            step("plan", "Plan trajectory", "Align the needle so its path remains visible in-plane.", "needle visibility"),
            step("advance", "Advance", "Move toward the target with short, controlled depth changes.", "target error"),
            step("confirm", "Confirm target", "Stop inside the target zone without entering the protected vessel.", "target contact"),
            step("recover", "Withdraw", "Withdraw along the same visible trajectory.", "safe recovery"),
        ],
        "success_metrics": ["target confidence", "needle visibility", "target error", "protected clearance", "trajectory length"],
        "truth_note": "This room provides a deterministic procedural B-mode training view and synchronized access metrics. NVIDIA's official ultrasound workflow remains a separately launched provider and requires its runtime prerequisites; neither path is a diagnostic or clinically validated ultrasound model.",
    },
    {
        "id": "biopsy-lesion-excision",
        "title": "Biopsy and lesion excision",
        "category": "Resection",
        "difficulty": "Advanced",
        "task": "Isaac-Reach-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Liver lesion phantom",
        "robot": "Dual dVRK PSM",
        "instrument": "Grasper and cutting tool controls",
        "objective": "Stabilize the target, create a planned circumferential margin, release the specimen, and avoid the protected structure.",
        "interaction": "Visible lesion target with topology-changing excision, margin, specimen-release and protected-clearance telemetry.",
        "fidelity": "topology_changing_excision",
        "guide_kind": "biopsy",
        "proxy_organ": None,
        "waypoints": ((-0.030, -0.020, 0.044), (-0.010, -0.030, 0.041), (0.014, -0.020, 0.040), (0.022, 0.002, 0.041), (0.008, 0.022, 0.042), (-0.016, 0.019, 0.043), (-0.030, -0.002, 0.044)),
        "steps": [
            step("identify", "Identify lesion", "Confirm the lesion boundary and protected structure before cutting.", "visual target"),
            step("stabilize", "Stabilize", "Apply gentle counter-traction with the second instrument.", "traction"),
            step("margin", "Create margin", "Trace the highlighted circumferential margin.", "margin distance"),
            step("release", "Release specimen", "Complete the final connecting segment and lift the specimen.", "topology release"),
            step("inspect", "Inspect bed", "Review margin consistency and protected-structure clearance.", "margin score"),
        ],
        "success_metrics": ["margin consistency", "specimen release", "protected clearance", "faces removed", "surface deformation"],
        "truth_note": "The lesion and specimen boundary modify the live OpenUSD surface. Histologic margins, bleeding and pathology are not simulated or clinically validated.",
    },
    {
        "id": "complication-recovery",
        "title": "Complication and dropped-object recovery",
        "category": "Complication management",
        "difficulty": "Research challenge",
        "task": "Isaac-Handover-Needle-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Multi-organ operative field",
        "robot": "Dual dVRK PSM",
        "instrument": "Two needle drivers",
        "objective": "Recognize a randomized visibility, calibration or dropped-object problem, stop unsafe motion, recover the object, and return to a stable operative state.",
        "interaction": "Failure-scenario injection with stop response, recovery path, protected-contact, reacquisition and stable-handback telemetry.",
        "fidelity": "interactive_recovery_scenarios",
        "guide_kind": "recovery",
        "proxy_organ": None,
        "waypoints": ((-0.045, -0.030, 0.065), (-0.016, -0.010, 0.046), (0.012, 0.008, 0.040), (0.040, 0.026, 0.058)),
        "steps": [
            step("recognize", "Recognize", "Identify the active failure and stop uncertain motion.", "failure recognition"),
            step("reframe", "Restore view", "Reposition or change camera until the object is observable.", "target visibility"),
            step("recover", "Recover object", "Approach slowly and reacquire a safe grasp.", "regrasp"),
            step("clear", "Clear anatomy", "Lift and move the recovered object away from protected surfaces.", "safe clearance"),
            step("handoff", "Stable hand-back", "Return to a known pose and explicitly complete or hand control back.", "stable recovery"),
        ],
        "success_metrics": ["time to stop", "reacquisition", "protected contacts", "interventions", "stable recovery"],
        "truth_note": "Failure cases are deterministic research scenarios. They train recognition, conservative recovery and human hand-back; they do not certify clinical emergency competence.",
    },
)


PROCEDURE_ROOMS = PROCEDURE_ROOMS + ADVANCED_PROCEDURE_ROOMS


PROCEDURE_SUITES: tuple[dict[str, Any], ...] = (
    {
        "id": "suturing-suite",
        "title": "Suturing and reconstruction",
        "description": "Progress from needle handling through continuous closure and pressure-tested anastomosis.",
        "rooms": ["needle-pickup", "needle-hoop-threading", "needle-passing-regrasp", "suture-threading-path", "running-suture", "intracorporeal-knot", "anastomosis-leak-test"],
    },
    {
        "id": "vascular-suite",
        "title": "Vascular access and control",
        "description": "Learn shunt placement, clip-and-divide technique and simulated bleeding control.",
        "rooms": ["vascular-shunt-insertion", "vessel-clip-divide", "bleeding-control"],
    },
    {
        "id": "gallbladder-suite",
        "title": "Gallbladder procedure pathway",
        "description": "Compose retraction, tissue-plane separation, clip-and-divide and specimen manipulation.",
        "rooms": ["gallbladder-reposition", "liver-retraction", "tissue-plane-dissection", "vessel-clip-divide", "biopsy-lesion-excision"],
    },
    {
        "id": "image-guided-suite",
        "title": "Image-guided intervention",
        "description": "Develop anatomy navigation, ultrasound targeting, access and complication recovery skills.",
        "rooms": ["synthetic-anatomy-navigation", "ultrasound-guided-access", "vascular-shunt-insertion", "complication-recovery"],
    },
)


PROCEDURES_BY_ID = {room["id"]: room for room in PROCEDURE_ROOMS}


def procedure_payload() -> dict[str, Any]:
    return {
        "schema": "dr.anmar.procedure-rooms.v2",
        "default": PROCEDURE_ROOMS[0]["id"],
        "rooms": [dict(room) for room in PROCEDURE_ROOMS],
        "suites": [dict(suite) for suite in PROCEDURE_SUITES],
        "fidelity_legend": {
            "nvidia_i4h_reference": "Published NVIDIA Isaac for Healthcare task boundary with rigid-body manipulation physics.",
            "native_object_physics": "Native rigid-body grasp/manipulation physics.",
            "path_guided_rehearsal": "Interactive tool control with ordered 3D guidance.",
            "interactive_suture_mechanics": "Constrained thread, tissue pins, tension telemetry, deformation, and cinch constraint.",
            "topology_changing_cut": "The swept tool removes faces from the live OpenUSD anatomy surface.",
            "deformable_surface_hybrid": "Compliant OpenUSD surface response over native gross-body grasp dynamics.",
            "anatomy_context": "Official anatomy variation used as a visual and spatial context.",
            "interactive_tube_insertion": "Flexible tube geometry with lumen alignment, depth, wall-load and patency telemetry.",
            "interactive_anastomosis_proxy": "Multi-bite closure with lumen-gap, constriction, pressure and leakage proxies.",
            "interactive_vascular_proxy": "Interactive clips, protected division interval and residual-flow telemetry.",
            "interactive_hemostasis_proxy": "Dynamic bleed-source, suction, compression, control and rebleed telemetry.",
            "topology_changing_dissection": "OpenUSD surface separation with plane and protected-structure telemetry.",
            "procedural_ultrasound_proxy": "Procedural B-mode rehearsal and synchronized target/needle metrics.",
            "topology_changing_excision": "Visible lesion target with topology-changing excision and margin telemetry.",
            "interactive_recovery_scenarios": "Injected failures with stop, reacquisition, safety and hand-back telemetry.",
        },
        "provenance_legend": {
            "nvidia_i4h_reference": "Behavior published by NVIDIA Isaac for Healthcare.",
            "dr_anmar_nvidia_stack_extension": "Dr.Anmar research behavior built on NVIDIA Isaac Sim, Isaac Lab, PhysX and OpenUSD; not an upstream NVIDIA task.",
        },
    }
