# Copyright (c) 2026, Dr.Anmar Project Developers.
# SPDX-License-Identifier: BSD-3-Clause

"""Clinician-facing composed operating-room presets for Dr.Anmar."""

from __future__ import annotations

from typing import Any


CT_MULTI_ORGAN = "OR_scene_CTLiver-Prostate-Bladder"
MAISI_LIVER_27 = "OR_scene_MAISI_imagesTr_liver_27_relabel_resample1_syn_seed6_postprocess"
MAISI_S0253 = "OR_scene_MAISI_s0253_ct_relabel_resample1_syn_seed6_postprocess"
MAISI_S0702 = "OR_scene_MAISI_s0702_ct_relabel_resample2_syn_seed6_postprocess"
MAISI_S0994 = "OR_scene_MAISI_s0994_ct_relabel_resample2_syn_seed6_postprocess"
MAISI_S1269 = "OR_scene_MAISI_s1269_ct_relabel_resample1_syn_seed6_postprocess"
SURGICAL_S1371 = "OR_scene_s1371"


def step(step_id: str, title: str, instruction: str, signal: str) -> dict[str, str]:
    return {"id": step_id, "title": title, "instruction": instruction, "signal": signal}


PROCEDURE_ROOMS: tuple[dict[str, Any], ...] = (
    {
        "id": "needle-pickup",
        "title": "Needle pickup",
        "category": "Needle skills",
        "difficulty": "Foundation",
        "task": "Isaac-Lift-Needle-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "CT liver field",
        "robot": "dVRK PSM",
        "instrument": "Large needle driver",
        "objective": "Approach the curved needle, grasp its body, lift it clear of the tray, and hold it stably.",
        "interaction": "Rigid curved needle with physical contact, grasp and lift.",
        "fidelity": "nvidia_i4h_reference",
        "source_workflow": "robotic_surgery/lift_needle_organs",
        "show_waypoint_markers": False,
        "guide_kind": "pickup",
        "steps": [
            step("approach", "Approach", "Bring the open jaws toward the middle third of the curved needle.", "tool motion"),
            step("grasp", "Grasp", "Close the gripper around the needle body; Space toggles the jaws.", "gripper close"),
            step("lift", "Lift", "Raise the grasped needle above its starting plane.", "needle elevation"),
            step("orient", "Orient", "Rotate the needle into a controlled, readable presentation.", "tool orientation"),
            step("recover", "Recover", "Hold the final pose without dropping the needle.", "stable hold"),
        ],
        "truth_note": "Foundation room: rigid needle handling without thread or tissue interaction.",
    },
    {
        "id": "needle-transfer",
        "title": "Needle handover",
        "category": "Needle skills",
        "difficulty": "Intermediate",
        "task": "Isaac-Handover-Needle-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "CT liver field",
        "robot": "Dual dVRK PSM",
        "instrument": "Two needle drivers",
        "objective": "Pick up the curved needle, present it to the second instrument, transfer the grasp, and separate safely.",
        "interaction": "Native ORBIT-Surgical dual-arm needle rigid-body physics.",
        "fidelity": "native_object_physics",
        "guide_kind": "handover",
        "steps": [
            step("pickup", "Pick up", "Instrument 1 secures the middle third of the needle.", "first grasp"),
            step("present", "Present", "Move the needle into a stable shared workspace.", "object movement"),
            step("receive", "Receive", "Instrument 2 closes on the exposed needle body.", "second grasp"),
            step("release", "Release", "Instrument 1 opens only after the receiving grasp is stable.", "gripper exchange"),
            step("separate", "Separate", "Move both tools apart while retaining the needle.", "stable recovery"),
        ],
        "truth_note": "The transfer uses the upstream dual-PSM needle environment; success scoring remains a research measure.",
    },
    {
        "id": "suture-threading-path",
        "title": "Single interrupted stitch",
        "category": "Needle skills",
        "difficulty": "Intermediate",
        "task": "Isaac-Handover-Needle-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Liver surface",
        "robot": "Dual dVRK PSM",
        "instrument": "Two needle drivers",
        "objective": "Drive the curved needle through tissue, pull the attached suture through the entry and exit, close the loop, and cinch it before recovery.",
        "interaction": "Native needle, strand, attachment, self-contact, puncture and volumetric-tissue mechanics.",
        "fidelity": "native_suturing",
        "guide_kind": "threading",
        "steps": [
            step("pickup", "Pick up", "Secure the needle away from its tip.", "gripper close"),
            step("entry", "Align entry", "Place the needle tip inside the cyan entry target.", "waypoint 1"),
            step("arc", "Pass through", "Rotate through the amber middle target and pull thread through the tissue.", "thread tension"),
            step("exit", "Exit tissue", "Bring the needle tip out through the green exit target.", "exit anchor"),
            step("knot", "Close and cinch", "Return the needle around the entry and pull until the loop cinches.", "knot constraint"),
            step("recover", "Recover", "Move the needle clear while preserving the tightened suture.", "stable hold"),
        ],
        "truth_note": "Launches only when one NVIDIA-stack worker owns the tissue, needle, strand, attachment and puncture state. No web-side strand or puncture substitute is permitted.",
    },
    {
        "id": "liver-cutting-path",
        "title": "Liver incision practice",
        "category": "Dissection planning",
        "difficulty": "Intermediate",
        "task": "Isaac-Reach-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Liver",
        "robot": "dVRK PSM",
        "instrument": "PSM training tool",
        "objective": "Open a continuous incision through the liver surface mesh while keeping the tool inside the ordered safety corridor.",
        "interaction": "Native topology-changing tissue with two-way tool contact and solver-owned cut state.",
        "fidelity": "native_topology_change",
        "guide_kind": "cutting_path",
        "steps": [
            step("plan", "Inspect", "Identify the cyan start and the complete amber corridor before moving.", "camera review"),
            step("approach", "Approach", "Move above the start target and settle the tool orientation.", "waypoint 1"),
            step("trace", "Cut", "Keep the tool on the tissue and open a continuous incision along every corridor target.", "topology change"),
            step("finish", "Finish", "Reach the green endpoint and inspect the opened mesh edges.", "cut endpoint"),
            step("recover", "Recover", "Lift away from the planned incision corridor.", "tool clearance"),
        ],
        "truth_note": "Launches only on the CRESSim-MPM/topology worker with a promoted physical asset. Dr.Anmar does not delete OpenUSD faces from tool gestures.",
    },
    {
        "id": "liver-retraction",
        "title": "Liver retraction practice",
        "category": "Tissue handling",
        "difficulty": "Intermediate",
        "task": "Isaac-Reach-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Liver",
        "robot": "dVRK PSM",
        "instrument": "Atraumatic grasper control",
        "objective": "Grasp the liver-shaped training target, lift it into a retracted position, and maintain a stable exposure.",
        "interaction": "Native PhysX FEM or coupled Newton VBD liver retraction with two-way instrument contact.",
        "fidelity": "native_volume_deformable",
        "guide_kind": "retraction",
        "steps": [
            step("inspect", "Inspect", "Choose a broad, accessible grasp region on the target.", "camera review"),
            step("approach", "Approach", "Bring the open jaws to the retraction target.", "tool motion"),
            step("grasp", "Grasp", "Close and confirm the target follows the tool.", "object coupling"),
            step("retract", "Retract", "Lift and move the target to expose the working area.", "object displacement"),
            step("hold", "Hold", "Maintain stable exposure before release.", "stable hold"),
        ],
        "truth_note": "The patient-derived tetrahedral liver asset is authored. This room launches only after its native deformable worker, attachments and instrument contact are promoted together.",
    },
    {
        "id": "gallbladder-reposition",
        "title": "Gallbladder repositioning",
        "category": "Tissue handling",
        "difficulty": "Intermediate",
        "task": "Isaac-Lift-Block-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Gallbladder",
        "robot": "dVRK PSM",
        "instrument": "Atraumatic grasper control",
        "objective": "Pick up the gallbladder-shaped target, reposition it to the indicated workspace, and release deliberately.",
        "interaction": "Native volumetric gallbladder deformation with two-way instrument contact and asset-authored attachments.",
        "fidelity": "native_volume_deformable",
        "guide_kind": "reposition",
        "steps": [
            step("approach", "Approach", "Move to the broad body of the target with the gripper open.", "tool motion"),
            step("grasp", "Grasp", "Close gently and confirm target motion.", "object coupling"),
            step("lift", "Lift", "Clear the starting surface before translating.", "object elevation"),
            step("place", "Place", "Move into the green placement region and open the jaws.", "target displacement"),
            step("recover", "Recover", "Withdraw without disturbing the placed target.", "tool clearance"),
        ],
        "truth_note": "Requires a tetrahedral gallbladder asset and native PhysX FEM or coupled Newton VBD worker. No rigid-core deformation proxy is used.",
    },
    {
        "id": "bladder-handover",
        "title": "Bladder-part bimanual relocation",
        "category": "Tissue handling",
        "difficulty": "Advanced",
        "task": "Isaac-Handover-Block-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Bladder",
        "robot": "Dual dVRK PSM",
        "instrument": "Two atraumatic grasper controls",
        "objective": "Move a bladder-shaped training target between instruments and place it in a new operative position.",
        "interaction": "Native volumetric bladder deformation under dual-arm two-way contact.",
        "fidelity": "native_volume_deformable",
        "guide_kind": "handover",
        "steps": [
            step("pickup", "Pick up", "Instrument 1 lifts the target clear of the table.", "first grasp"),
            step("present", "Present", "Stabilize the target in the shared workspace.", "object motion"),
            step("receive", "Receive", "Instrument 2 grasps before Instrument 1 releases.", "second grasp"),
            step("place", "Relocate", "Move the retained target to its indicated new position.", "object displacement"),
            step("recover", "Recover", "Release and separate both instruments.", "stable release"),
        ],
        "truth_note": "Requires a tetrahedral bladder asset and native PhysX FEM or coupled Newton VBD worker. No web-side surface deformation is used.",
    },
    {
        "id": "synthetic-anatomy-navigation",
        "title": "Anatomy-variation navigation",
        "category": "Visual robustness",
        "difficulty": "Research challenge",
        "task": "Isaac-Reach-PSM-IK-Rel-v0",
        "anatomy_scene": SURGICAL_S1371,
        "anatomy_focus": "Multi-organ surgical anatomy",
        "robot": "dVRK PSM",
        "instrument": "PSM training tool",
        "objective": "Navigate an ordered target path in a distinct patient-anatomy geometry and record a comparable trajectory.",
        "interaction": "Official OpenUSD anatomy variation with native relative-IK tool control and 3D waypoint scoring.",
        "fidelity": "anatomy_context",
        "guide_kind": "navigation",
        "steps": [
            step("survey", "Survey", "Use the endoscope to identify anatomy and all visible targets.", "camera review"),
            step("approach", "Approach", "Move to the first cyan target.", "waypoint 1"),
            step("navigate", "Navigate", "Visit each amber target in order.", "ordered waypoints"),
            step("finish", "Finish", "Reach the green endpoint.", "final waypoint"),
            step("recover", "Recover", "Return to a safe observation pose.", "tool clearance"),
        ],
        "truth_note": "This scene evaluates navigation across anatomy variation; it is not a clinical procedure model.",
    },
)


# These rooms deliberately reuse a small set of native ORBIT-Surgical tasks.
# The native task supplies the robot and stable contact loop; Dr.Anmar composes
# procedure-specific OpenUSD geometry, guidance, mutable tissue and telemetry on
# top.  This keeps every room recordable with the same observation/action schema.
ADVANCED_PROCEDURE_ROOMS: tuple[dict[str, Any], ...] = (
    {
        "id": "vascular-shunt-insertion",
        "title": "Vascular shunt insertion",
        "category": "Access and device placement",
        "difficulty": "Intermediate",
        "task": "Isaac-Lift-Block-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Liver vascular field",
        "robot": "dVRK PSM",
        "instrument": "Atraumatic grasper",
        "objective": "Acquire a flexible shunt, align its tip with the vessel lumen, advance without wall overload, and verify stable placement and patency.",
        "interaction": "Native flexible shunt, deformable vessel contact and solver-derived insertion telemetry.",
        "fidelity": "native_flexible_shunt",
        "guide_kind": "tube_insertion",
        "waypoints": ((-0.058, -0.025, 0.060), (-0.034, -0.012, 0.052), (-0.008, 0.002, 0.047), (0.024, 0.018, 0.044)),
        "steps": [
            step("acquire", "Acquire shunt", "Close on the reinforced middle of the flexible shunt.", "secure grasp"),
            step("align", "Align lumen", "Bring the shunt tip coaxially to the cyan vessel opening.", "radial and angular error"),
            step("insert", "Advance", "Advance along the vessel axis while watching wall load and buckling.", "insertion depth"),
            step("seat", "Seat", "Reach the planned depth without exceeding the wall-load advisory band.", "target depth"),
            step("verify", "Verify patency", "Stop motion and confirm placement, low wall load and simulated flow.", "solver patency"),
        ],
        "success_metrics": ["insertion depth", "radial error", "solver wall load", "buckling events", "solver patency"],
        "truth_note": "Requires native flexible-body and vessel-contact assets. Dr.Anmar does not synthesize buckling, wall load or patency from tool coordinates.",
    },
    {
        "id": "running-suture",
        "title": "Running suturing",
        "category": "Suturing",
        "difficulty": "Advanced",
        "task": "Isaac-Handover-Needle-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Liver wound edge",
        "robot": "Dual dVRK PSM",
        "instrument": "Two needle drivers",
        "objective": "Place a continuous row of tissue bites with consistent spacing and tension, then secure the final loop.",
        "interaction": "Native persistent strand, repeated puncture, tissue attachment and solver-derived tension across multiple bites.",
        "fidelity": "native_suturing",
        "guide_kind": "running_suture",
        "target_anchors": 6,
        "target_stitches": 3,
        "waypoints": ((-0.050, -0.026, 0.030), (-0.031, -0.012, 0.039), (-0.010, 0.000, 0.044), (0.011, 0.011, 0.041), (0.032, 0.021, 0.035), (0.050, 0.030, 0.031)),
        "steps": [
            step("first_bite", "First bite", "Drive the first controlled entry and exit across the wound.", "anchors 1-2"),
            step("second_bite", "Second bite", "Advance along the wound with similar bite width and depth.", "anchors 3-4"),
            step("third_bite", "Third bite", "Complete the final planned bite without crossing the thread.", "anchors 5-6"),
            step("tension", "Balance tension", "Pull until the wound edges approximate without over-tightening.", "closure gap"),
            step("secure", "Secure", "Cinch the terminal loop and recover with stable thread tension.", "knot constraint"),
        ],
        "success_metrics": ["stitch count", "bite spacing", "closure gap", "peak tension", "over-tension events"],
        "truth_note": "Requires the same native tissue/needle/strand stack as interrupted suturing. Gesture-scored anchors and cinch constraints have been removed.",
    },
    {
        "id": "intracorporeal-knot",
        "title": "Intracorporeal knot tying",
        "category": "Suturing",
        "difficulty": "Advanced",
        "task": "Isaac-Handover-Needle-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Liver wound edge",
        "robot": "Dual dVRK PSM",
        "instrument": "Two needle drivers",
        "objective": "Form opposing throws, seat a square knot, and tighten it without tissue strangulation or loop slippage.",
        "interaction": "Native strand self-contact and two-arm manipulation with solver-derived knot topology and tension.",
        "fidelity": "native_suturing",
        "guide_kind": "knot_tying",
        "target_anchors": 2,
        "target_throws": 3,
        "waypoints": ((-0.035, -0.020, 0.043), (-0.012, 0.008, 0.052), (0.018, -0.005, 0.049), (-0.012, -0.023, 0.043), (0.024, 0.015, 0.040)),
        "steps": [
            step("loop", "Form loop", "Cross the working strand around the opposing instrument.", "loop crossing"),
            step("throw_one", "First throw", "Pull the first throw down evenly toward the tissue.", "throw 1"),
            step("reverse", "Reverse direction", "Create the opposing crossing required for a square knot.", "crossing direction"),
            step("throw_two", "Second throw", "Seat the opposing throw without loosening the first.", "throw 2"),
            step("secure", "Secure and inspect", "Complete the final throw and inspect tension and slippage.", "knot security"),
        ],
        "success_metrics": ["throw count", "alternating crossings", "knot tightness", "solver slippage", "peak tension"],
        "truth_note": "Requires native strand self-contact and attachment. Dr.Anmar evaluates the resulting knot but never creates or tightens one from hand trajectories.",
    },
    {
        "id": "nvidia-strand-ring-threading",
        "title": "PSM strand ring threading",
        "category": "Deformable-object skills",
        "difficulty": "Intermediate",
        "task": "Isaac-Thread-PSM-IK-Rel-v0",
        "anatomy_scene": "",
        "anatomy_focus": "SoftMimicGen dry-lab field",
        "robot": "dVRK PSM",
        "instrument": "PSM forceps",
        "objective": "Grasp the native deformable strand and pass it through the rigid ring using NVIDIA's released SoftMimicGen task.",
        "interaction": "NVIDIA SoftMimicGen FEM strand, rigid ring contact, relative Cartesian IK and recorded expert demonstrations.",
        "fidelity": "nvidia_softmimicgen_threading",
        "implementation_origin": "nvidia_softmimicgen_reference",
        "platform_foundation": "NVIDIA SoftMimicGen, Isaac Sim 5.1, pinned Isaac Lab fork, PhysX and OpenUSD",
        "guide_kind": "softmimicgen_threading",
        "hide_anatomy": True,
        "show_waypoint_markers": False,
        "waypoints": (),
        "steps": [
            step("approach", "Approach", "Move the open PSM jaws to the free strand without contacting the ring.", "tool-to-strand alignment"),
            step("grasp", "Grasp", "Close around the strand and verify that the FEM body follows the physical jaws.", "physical strand grasp"),
            step("align", "Align", "Bring the grasped strand to the ring centre while preserving clearance from the tube.", "ring-centre alignment"),
            step("thread", "Thread", "Advance through the opening until the strand crosses the ring plane.", "native ring crossing"),
            step("recover", "Recover", "Hold the completed pass steady, then withdraw without pulling back through the ring.", "stable completion"),
        ],
        "success_metrics": ["upstream success condition", "ring contact", "strand nodal state", "tool trajectory"],
        "truth_note": "This is NVIDIA's released direct-strand threading task. It contains no needle, tissue puncture, knot or strand self-contact claim.",
    },
    {
        "id": "needle-hoop-threading",
        "title": "Threaded needle ring pass",
        "category": "Needle skills",
        "difficulty": "Intermediate",
        "task": "Isaac-Handover-Needle-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Dry-lab training field",
        "robot": "Dual dVRK PSM",
        "instrument": "Two needle drivers",
        "objective": "Pick up the threaded needle, rotate its sharp tip through the physical ring, and complete a bimanual handoff using native rigid and deformable-body physics.",
        "interaction": "Native dry-lab strand, needle attachment, self-contact and rigid hoop collision.",
        "fidelity": "native_suturing_drylab",
        "implementation_origin": "dr_anmar_nvidia_stack_extension",
        "platform_foundation": "NVIDIA Isaac Sim 5.1, Isaac Lab, PhysX and OpenUSD",
        "nvidia_reference_tasks": ["robotic_surgery/lift_needle", "robotic_surgery/reach_dual_psm"],
        "guide_kind": "hoop_threading",
        "hide_anatomy": True,
        "show_waypoint_markers": False,
        "hoop_inner_radius_m": 0.017,
        "hoop_tube_radius_m": 0.0025,
        "target_throws": 0,
        "waypoints": ((-0.035, 0.000, 0.065), (0.000, 0.000, 0.065), (0.012, 0.000, 0.065)),
        "steps": [
            step("pickup", "Pick up the threaded needle", "Close on the middle third of the needle and confirm that the suture follows continuously from its eye.", "needle and suture custody"),
            step("pass", "Pass the hoop", "Center the sharp tip, follow the needle curvature through the opening, and clear the ring without contact.", "clean plane crossing"),
            step("handoff", "Complete the handoff", "Instrument 2 receives the needle only after a physical grasp is confirmed, then Instrument 1 releases.", "physical needle custody"),
            step("inspect", "Inspect and recover", "Confirm the needle cleared the ring without contact and remained physically attached to the receiving instrument.", "pass and custody evidence"),
        ],
        "success_metrics": ["clean hoop pass", "rigid ring contacts", "physical needle custody", "native strand continuity"],
        "truth_note": "Launches only after the native strand asset and attachment are promoted. The former projected strand path has been deleted.",
    },
    {
        "id": "needle-passing-regrasp",
        "title": "Needle passing and regrasping",
        "category": "Needle skills",
        "difficulty": "Intermediate",
        "task": "Isaac-Handover-Needle-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Liver operative field",
        "robot": "Dual dVRK PSM",
        "instrument": "Two needle drivers",
        "objective": "Pass the needle through an ordered spatial target, regrasp on its body, and present a usable needle orientation for the next stitch.",
        "interaction": "Native dual-arm needle grasping plus ordered 3D pass targets, receiver approach, stable exchange and recovery scoring.",
        "fidelity": "native_object_physics",
        "guide_kind": "needle_pass",
        "waypoints": ((-0.040, -0.028, 0.050), (-0.014, -0.006, 0.062), (0.012, 0.012, 0.061), (0.040, 0.026, 0.050)),
        "steps": [
            step("orient", "Orient needle", "Rotate the needle into a readable presentation.", "needle pose"),
            step("pass", "Pass target", "Move the needle body through the highlighted spatial target.", "ordered waypoint"),
            step("receive", "Receive", "Close Instrument 2 on a safe section of the exposed needle body.", "second grasp"),
            step("release", "Release", "Open Instrument 1 after the receiving grasp is stable.", "handover"),
            step("present", "Present", "Recover with the needle ready for the next tissue bite.", "final pose"),
        ],
        "success_metrics": ["target passage", "dual-grasp overlap", "drop events", "final presentation", "motion economy"],
        "truth_note": "Needle and robot contact use native simulator physics. Usable-grasp and presentation scores are research measures awaiting clinician thresholds.",
    },
    {
        "id": "anastomosis-leak-test",
        "title": "Anastomosis and leak test",
        "category": "Reconstruction",
        "difficulty": "Research challenge",
        "task": "Isaac-Handover-Needle-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Bowel-style lumen phantom",
        "robot": "Dual dVRK PSM",
        "instrument": "Two needle drivers",
        "objective": "Approximate two lumen ends with distributed stitches, secure the closure, and perform a simulated pressure leak test.",
        "interaction": "Native deformable lumen, suture strand and fluid-structure coupling under pressure.",
        "fidelity": "native_fluid_structure",
        "guide_kind": "anastomosis",
        "target_anchors": 8,
        "target_stitches": 4,
        "waypoints": ((-0.042, -0.026, 0.038), (-0.025, -0.006, 0.048), (-0.006, 0.014, 0.046), (0.014, 0.020, 0.041), (0.032, 0.004, 0.045), (0.015, -0.016, 0.048), (-0.010, -0.022, 0.043), (-0.035, -0.012, 0.039)),
        "steps": [
            step("align", "Align lumens", "Bring the two lumen ends together without twisting them.", "ring alignment"),
            step("posterior", "Posterior wall", "Place evenly distributed posterior bites.", "stitches 1-2"),
            step("anterior", "Anterior wall", "Complete the anterior closure while preserving lumen diameter.", "stitches 3-4"),
            step("secure", "Secure closure", "Tie and balance tension around the circumference.", "knot and constriction"),
            step("test", "Pressure test", "Hold still while the simulated lumen is pressurized and leakage is measured.", "leak rate"),
        ],
        "success_metrics": ["stitch distribution", "closure gap", "lumen narrowing", "solver leak rate", "peak tension"],
        "truth_note": "Requires a native fluid-structure worker. Pressure and leakage must come from that solver, never from a web-side formula.",
    },
    {
        "id": "vessel-clip-divide",
        "title": "Clip, ligate and divide",
        "category": "Vascular control",
        "difficulty": "Advanced",
        "task": "Isaac-Reach-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Gallbladder vascular field",
        "robot": "Dual dVRK PSM",
        "instrument": "Clip applier and scissors controls",
        "objective": "Expose a target vessel, place two secure clips with spacing, and divide only inside the protected interval.",
        "interaction": "Native deformable vessel, physical clips, topology change and vascular flow.",
        "fidelity": "native_vascular_flow",
        "guide_kind": "clip_divide",
        "waypoints": ((-0.045, -0.024, 0.045), (-0.020, -0.008, 0.043), (0.004, 0.004, 0.042), (0.025, 0.015, 0.041), (0.047, 0.025, 0.045)),
        "steps": [
            step("expose", "Expose vessel", "Use the second instrument to maintain a stable view.", "exposure"),
            step("clip_one", "Place proximal clip", "Seat the first clip squarely across the target vessel.", "clip 1"),
            step("clip_two", "Place distal clip", "Place a second clip with a safe division interval.", "clip 2"),
            step("divide", "Divide", "Cut only between the two confirmed clips.", "protected division"),
            step("inspect", "Inspect", "Confirm retained clips and simulated flow arrest.", "residual flow"),
        ],
        "success_metrics": ["clip count", "clip spacing", "division location", "protected contacts", "solver residual flow"],
        "truth_note": "Requires native clip contact, vessel deformation, division and flow. Residual flow is never inferred from gripper closure.",
    },
    {
        "id": "bleeding-control",
        "title": "Bleeding control and hemostasis",
        "category": "Complication management",
        "difficulty": "Research challenge",
        "task": "Isaac-Reach-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Liver vascular field",
        "robot": "Dual dVRK PSM",
        "instrument": "Grasper, suction and clip controls",
        "objective": "Maintain exposure, localize the bleeding source, reduce visual contamination, and achieve stable simulated hemostasis.",
        "interaction": "Native fluid, vessel compression, clipping and hemostasis state.",
        "fidelity": "native_hemostasis",
        "guide_kind": "hemostasis",
        "waypoints": ((-0.040, -0.026, 0.060), (-0.018, -0.009, 0.048), (0.005, 0.004, 0.041), (0.026, 0.015, 0.046)),
        "steps": [
            step("expose", "Maintain exposure", "Keep the source visible while bringing suction into the field.", "visibility"),
            step("localize", "Localize source", "Center the instrument on the bleeding origin.", "source distance"),
            step("control", "Temporary control", "Apply compression or suction to reduce the active flow.", "bleed rate"),
            step("definitive", "Definitive control", "Place the indicated clip or maintain the planned control action.", "flow arrest"),
            step("observe", "Observe for rebleed", "Hold the field stable and confirm the source remains controlled.", "rebleed test"),
        ],
        "success_metrics": ["time to localization", "solver blood loss", "minimum visibility", "time to control", "rebleed"],
        "truth_note": "Requires native fluid and coagulation capabilities. Dr.Anmar does not manufacture bleeding or control from distance thresholds.",
    },
    {
        "id": "tissue-plane-dissection",
        "title": "Tissue-plane dissection",
        "category": "Dissection",
        "difficulty": "Advanced",
        "task": "Isaac-Reach-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Gallbladder and liver plane",
        "robot": "Dual dVRK PSM",
        "instrument": "Grasper and dissector controls",
        "objective": "Create exposure and separate the highlighted tissue plane while preserving the protected duct and vessel corridors.",
        "interaction": "Native topology-changing tissue separation with traction and protected-structure contact.",
        "fidelity": "native_topology_change",
        "guide_kind": "dissection",
        "waypoints": ((-0.052, -0.025, 0.047), (-0.030, -0.012, 0.044), (-0.006, 0.000, 0.042), (0.019, 0.012, 0.043), (0.045, 0.024, 0.049)),
        "steps": [
            step("expose", "Create traction", "Use the second instrument to open the intended plane.", "bimanual exposure"),
            step("enter", "Enter plane", "Start at the cyan low-risk edge.", "plane entry"),
            step("separate", "Separate", "Advance through the amber tissue plane with short controlled motions.", "topology separation"),
            step("protect", "Protect structures", "Stay outside the marked duct and vessel corridors.", "protected clearance"),
            step("inspect", "Inspect plane", "Stop and inspect the completed separation before recovery.", "plane completion"),
        ],
        "success_metrics": ["plane progress", "off-plane distance", "protected contacts", "traction stability", "surface injury"],
        "truth_note": "Requires the native topology worker and promoted tissue-plane asset. The workstation no longer separates mesh faces from a traced path.",
    },
    {
        "id": "ultrasound-guided-access",
        "title": "Ultrasound-guided needle access",
        "category": "Image-guided intervention",
        "difficulty": "Advanced",
        "task": "Isaac-Reach-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": MAISI_S0253,
        "anatomy_focus": "Synthetic abdominal target",
        "robot": "Dual dVRK PSM",
        "instrument": "Instrument 1 ultrasound probe · Instrument 2 access needle",
        "objective": "Acquire a simulated ultrasound target, plan an in-plane trajectory, and advance to the target while avoiding the protected vessel.",
        "interaction": "NVIDIA medical-ultrasound workflow output synchronized with physical probe and needle poses.",
        "fidelity": "nvidia_medical_ultrasound",
        "guide_kind": "ultrasound_access",
        "waypoints": ((-0.050, -0.030, 0.075), (-0.026, -0.013, 0.058), (-0.004, 0.003, 0.047), (0.018, 0.017, 0.037)),
        "steps": [
            step("survey", "Survey", "Move the probe until the target is centered and confidence is stable.", "target confidence"),
            step("plan", "Plan trajectory", "Align the needle so its path remains visible in-plane.", "needle visibility"),
            step("advance", "Advance", "Move toward the target with short, controlled depth changes.", "target error"),
            step("confirm", "Confirm target", "Stop inside the target zone without entering the protected vessel.", "target contact"),
            step("recover", "Withdraw", "Withdraw along the same visible trajectory.", "safe recovery"),
        ],
        "success_metrics": ["target confidence", "needle visibility", "target error", "protected clearance", "trajectory length"],
        "truth_note": "Launches only through the NVIDIA healthcare ultrasound provider. The former drawn B-mode proxy has been removed.",
    },
    {
        "id": "biopsy-lesion-excision",
        "title": "Biopsy and lesion excision",
        "category": "Resection",
        "difficulty": "Advanced",
        "task": "Isaac-Reach-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Liver lesion phantom",
        "robot": "Dual dVRK PSM",
        "instrument": "Grasper and cutting tool controls",
        "objective": "Stabilize the target, create a planned circumferential margin, release the specimen, and avoid the protected structure.",
        "interaction": "Native topology-changing lesion excision with specimen contact and margin geometry.",
        "fidelity": "native_topology_change",
        "guide_kind": "biopsy",
        "waypoints": ((-0.030, -0.020, 0.044), (-0.010, -0.030, 0.041), (0.014, -0.020, 0.040), (0.022, 0.002, 0.041), (0.008, 0.022, 0.042), (-0.016, 0.019, 0.043), (-0.030, -0.002, 0.044)),
        "steps": [
            step("identify", "Identify lesion", "Confirm the lesion boundary and protected structure before cutting.", "visual target"),
            step("stabilize", "Stabilize", "Apply gentle counter-traction with the second instrument.", "traction"),
            step("margin", "Create margin", "Trace the highlighted circumferential margin.", "margin distance"),
            step("release", "Release specimen", "Complete the final connecting segment and lift the specimen.", "topology release"),
            step("inspect", "Inspect bed", "Review margin consistency and protected-structure clearance.", "margin score"),
        ],
        "success_metrics": ["margin consistency", "specimen release", "protected clearance", "faces removed", "surface deformation"],
        "truth_note": "Requires the native topology worker and promoted lesion asset. Histologic interpretation remains outside the simulator.",
    },
    {
        "id": "complication-recovery",
        "title": "Complication and dropped-object recovery",
        "category": "Complication management",
        "difficulty": "Research challenge",
        "task": "Isaac-Handover-Needle-Dual-PSM-IK-Rel-v0",
        "anatomy_scene": CT_MULTI_ORGAN,
        "anatomy_focus": "Multi-organ operative field",
        "robot": "Dual dVRK PSM",
        "instrument": "Two needle drivers",
        "objective": "Recognize a randomized visibility, calibration or dropped-object problem, stop unsafe motion, recover the object, and return to a stable operative state.",
        "interaction": "Failure-scenario injection with stop response, recovery path, protected-contact, reacquisition and stable-handback telemetry.",
        "fidelity": "interactive_recovery_scenarios",
        "guide_kind": "recovery",
        "waypoints": ((-0.045, -0.030, 0.065), (-0.016, -0.010, 0.046), (0.012, 0.008, 0.040), (0.040, 0.026, 0.058)),
        "steps": [
            step("recognize", "Recognize", "Identify the active failure and stop uncertain motion.", "failure recognition"),
            step("reframe", "Restore view", "Reposition or change camera until the object is observable.", "target visibility"),
            step("recover", "Recover object", "Approach slowly and reacquire a safe grasp.", "regrasp"),
            step("clear", "Clear anatomy", "Lift and move the recovered object away from protected surfaces.", "safe clearance"),
            step("handoff", "Stable hand-back", "Return to a known pose and explicitly complete or hand control back.", "stable recovery"),
        ],
        "success_metrics": ["time to stop", "reacquisition", "protected contacts", "interventions", "stable recovery"],
        "truth_note": "Failure cases are deterministic research scenarios. They train recognition, conservative recovery and human hand-back; they do not certify clinical emergency competence.",
    },
)


SONOGYM_ORTHOPEDIC_ROOMS: tuple[dict[str, Any], ...] = (
    {
        "id": "orthopedic-l4-ultrasound-navigation",
        "title": "L4 ultrasound navigation",
        "category": "Orthopedic ultrasound",
        "difficulty": "Foundation",
        "task": "Isaac-robot-US-guidance-v0",
        "anatomy_scene": "sonogym-lumbar-l4",
        "anatomy_focus": "CT-derived lumbar anatomy and L4 vertebra",
        "robot": "KUKA LBR with ultrasound probe",
        "instrument": "Robotic ultrasound probe",
        "objective": "Find the transverse ultrasound plane through the centre of L4 and hold a stable diagnostic view.",
        "interaction": "SonoGym native CT-derived ultrasound navigation, robot control, observations and reward.",
        "fidelity": "sonogym_native_ultrasound",
        "external_provider": "sonogym_orthopedics",
        "provider_mode": "l4_ultrasound_navigation",
        "guide_kind": "orthopedic_ultrasound_navigation",
        "waypoints": (),
        "steps": [
            step("survey", "Survey", "Sweep the lumbar surface and identify the L4 acoustic appearance.", "target visibility"),
            step("orient", "Orient", "Rotate into a transverse view without losing contact.", "probe orientation"),
            step("centre", "Centre L4", "Translate until the centre of L4 is aligned with the target plane.", "plane error"),
            step("hold", "Hold view", "Maintain the plane steadily before completing the attempt.", "view stability"),
        ],
        "success_metrics": ["plane error", "probe path length", "view stability", "episode reward"],
        "truth_note": "Runs the upstream SonoGym Isaac Lab task. SonoGym currently uses CT-derived rigid patient geometry; its authors identify soft-tissue deformation and real-system clinical validation as future work.",
    },
    {
        "id": "orthopedic-l4-surface-reconstruction",
        "title": "L4 ultrasound surface reconstruction",
        "category": "Orthopedic ultrasound",
        "difficulty": "Intermediate",
        "task": "Isaac-robot-US-reconstruction-v0",
        "anatomy_scene": "sonogym-lumbar-l4",
        "anatomy_focus": "CT-derived lumbar anatomy and L4 surface",
        "robot": "KUKA LBR with ultrasound probe",
        "instrument": "Robotic ultrasound probe",
        "objective": "Acquire complementary ultrasound sweeps that reconstruct the L4 bone surface with efficient coverage.",
        "interaction": "SonoGym native reconstruction state, coverage observation, submodular reward and Isaac Lab stepping.",
        "fidelity": "sonogym_native_reconstruction",
        "external_provider": "sonogym_orthopedics",
        "provider_mode": "l4_surface_reconstruction",
        "guide_kind": "orthopedic_ultrasound_reconstruction",
        "waypoints": (),
        "steps": [
            step("localize", "Localize L4", "Acquire an initial view of the L4 target surface.", "initial localization"),
            step("sweep", "Build coverage", "Sweep through complementary views instead of repeating the same plane.", "surface coverage"),
            step("inspect", "Inspect gaps", "Use the reconstruction observation to find uncovered regions.", "uncovered surface"),
            step("complete", "Complete model", "Finish with stable, efficient coverage of the target surface.", "coverage efficiency"),
        ],
        "success_metrics": ["surface coverage", "uncovered points", "trajectory length", "episode reward"],
        "truth_note": "Runs SonoGym's upstream anatomy-reconstruction environment and observation. The reconstructed target is the simulated L4 surface, not a validated clinical diagnosis.",
    },
    {
        "id": "orthopedic-l4-ultrasound-guided-surgery",
        "title": "L4 ultrasound-guided orthopedic trajectory",
        "category": "Orthopedic ultrasound",
        "difficulty": "Advanced research",
        "task": "Isaac-robot-US-guided-surgery-v0",
        "anatomy_scene": "sonogym-lumbar-l4",
        "anatomy_focus": "CT-derived lumbar anatomy and protected L4 target",
        "robot": "FR3 ultrasound robot + KUKA orthopedic instrument robot",
        "instrument": "Ultrasound probe and orthopedic drill trajectory",
        "objective": "Localize L4 with ultrasound, align the orthopedic trajectory, and advance while respecting SonoGym's safety cost.",
        "interaction": "SonoGym native dual-robot ultrasound-guided surgery environment with safe-action constraints.",
        "fidelity": "sonogym_native_guided_surgery",
        "external_provider": "sonogym_orthopedics",
        "provider_mode": "l4_ultrasound_guided_surgery",
        "guide_kind": "orthopedic_ultrasound_guided_surgery",
        "waypoints": (),
        "steps": [
            step("localize", "Localize", "Acquire and stabilize the L4 ultrasound target.", "target visibility"),
            step("plan", "Plan", "Align the approach trajectory with the target and safety corridor.", "trajectory alignment"),
            step("advance", "Advance", "Use short, controlled actions while monitoring ultrasound and safety state.", "target error"),
            step("verify", "Verify", "Stop at the planned endpoint and inspect the final target and cost state.", "safe endpoint"),
        ],
        "success_metrics": ["target error", "trajectory length", "unsafe-action cost", "episode reward"],
        "truth_note": "Runs SonoGym's upstream ultrasound-guided surgery task. It is a research benchmark around L4 targeting, not a clinical drilling simulator or permission for autonomous intervention.",
    },
)


PROCEDURE_ROOMS = PROCEDURE_ROOMS + ADVANCED_PROCEDURE_ROOMS + SONOGYM_ORTHOPEDIC_ROOMS


PROCEDURE_SUITES: tuple[dict[str, Any], ...] = (
    {
        "id": "suturing-suite",
        "title": "Suturing and reconstruction",
        "description": "Progress from needle handling through continuous closure and pressure-tested anastomosis.",
        "rooms": ["nvidia-strand-ring-threading", "needle-pickup", "needle-hoop-threading", "needle-passing-regrasp", "suture-threading-path", "running-suture", "intracorporeal-knot", "anastomosis-leak-test"],
    },
    {
        "id": "vascular-suite",
        "title": "Vascular access and control",
        "description": "Learn shunt placement, clip-and-divide technique and simulated bleeding control.",
        "rooms": ["vascular-shunt-insertion", "vessel-clip-divide", "bleeding-control"],
    },
    {
        "id": "gallbladder-suite",
        "title": "Gallbladder procedure pathway",
        "description": "Compose retraction, tissue-plane separation, clip-and-divide and specimen manipulation.",
        "rooms": ["gallbladder-reposition", "liver-retraction", "tissue-plane-dissection", "vessel-clip-divide", "biopsy-lesion-excision"],
    },
    {
        "id": "image-guided-suite",
        "title": "Image-guided intervention",
        "description": "Develop anatomy navigation, ultrasound targeting, access and complication recovery skills.",
        "rooms": ["synthetic-anatomy-navigation", "ultrasound-guided-access", "vascular-shunt-insertion", "complication-recovery"],
    },
    {
        "id": "orthopedic-ultrasound-suite",
        "title": "Orthopedic robotic ultrasound",
        "description": "Progress from L4 plane localization through surface reconstruction to ultrasound-guided orthopedic trajectory research.",
        "rooms": [
            "orthopedic-l4-ultrasound-navigation",
            "orthopedic-l4-surface-reconstruction",
            "orthopedic-l4-ultrasound-guided-surgery",
        ],
    },
)


PROCEDURES_BY_ID = {room["id"]: room for room in PROCEDURE_ROOMS}


def procedure_payload() -> dict[str, Any]:
    return {
        "schema": "dr.anmar.procedure-rooms.v2",
        "default": PROCEDURE_ROOMS[0]["id"],
        "rooms": [dict(room) for room in PROCEDURE_ROOMS],
        "suites": [dict(suite) for suite in PROCEDURE_SUITES],
        "fidelity_legend": {
            "nvidia_i4h_reference": "Published NVIDIA Isaac for Healthcare task boundary with rigid-body manipulation physics.",
            "native_object_physics": "Native rigid-body grasp/manipulation physics.",
            "anatomy_context": "Official anatomy variation used as a visual and spatial context.",
            "native_volume_deformable": "Native NVIDIA volumetric tissue and two-way instrument contact.",
            "native_suturing": "Native tissue, needle, strand, attachment, self-contact and puncture mechanics.",
            "native_suturing_drylab": "Native needle, strand, attachment and self-contact mechanics.",
            "nvidia_softmimicgen_threading": "NVIDIA SoftMimicGen direct-strand threading with native PhysX FEM and rigid ring contact.",
            "native_topology_change": "Native tissue topology change and two-way instrument contact.",
            "native_flexible_shunt": "Native flexible shunt and vessel contact mechanics.",
            "native_fluid_structure": "Native deformable tissue and fluid-structure coupling.",
            "native_vascular_flow": "Native deformable vessel and vascular flow.",
            "native_hemostasis": "Native fluid and hemostasis mechanics.",
            "nvidia_medical_ultrasound": "NVIDIA medical-ultrasound workflow output.",
            "sonogym_native_ultrasound": "SonoGym native CT-derived orthopedic ultrasound navigation.",
            "sonogym_native_reconstruction": "SonoGym native ultrasound-based L4 surface reconstruction.",
            "sonogym_native_guided_surgery": "SonoGym native dual-robot ultrasound-guided orthopedic surgery benchmark.",
            "interactive_recovery_scenarios": "Injected failures with stop, reacquisition, safety and hand-back telemetry.",
        },
        "provenance_legend": {
            "nvidia_i4h_reference": "Behavior published by NVIDIA Isaac for Healthcare.",
            "dr_anmar_nvidia_stack_extension": "Dr.Anmar research behavior built on NVIDIA Isaac Sim, Isaac Lab, PhysX and OpenUSD; not an upstream NVIDIA task.",
            "nvidia_softmimicgen_reference": "Behavior released by NVIDIA SoftMimicGen and exposed through Dr.Anmar without changing its action or physics task.",
        },
    }
