# Copyright (c) 2026, Dr.Anmar Project Developers.
# SPDX-License-Identifier: BSD-3-Clause

"""Doctor-first curriculum and research references for Dr.Anmar Studio."""

from __future__ import annotations


COURSES = [
    {
        "id": "robot-foundations",
        "number": "01",
        "title": "Robot foundations",
        "short_title": "Foundations",
        "description": "Learn how a surgical robot sees, moves, and holds a tool before teaching it a procedure.",
        "lessons": [
            {
                "id": "psm-precision-reach",
                "title": "Move a patient-side instrument",
                "eyebrow": "Runnable lab · 12 min",
                "task": "Isaac-Reach-PSM-IK-Rel-v0",
                "video": None,
                "mode": "live",
                "summary": "Guide one PSM tool to a target pose. Think of this as hand-eye coordination for a robot.",
                "goal": "Reach the target smoothly while keeping movements small and controlled.",
                "concepts": ["6D pose", "inverse kinematics", "action"],
            },
            {
                "id": "ecm-camera-control",
                "title": "Position the endoscopic camera",
                "eyebrow": "Runnable lab · 10 min",
                "task": "Isaac-Reach-ECM-IK-Rel-v0",
                "video": None,
                "mode": "live",
                "summary": "Move the ECM camera to improve the operative view without moving the surgical tool.",
                "goal": "Center the target and keep it visible, like framing a subject with a camera.",
                "concepts": ["observation", "camera pose", "workspace"],
            },
            {
                "id": "dual-arm-coordination",
                "title": "Coordinate two instruments",
                "eyebrow": "Runnable lab · 15 min",
                "task": "Isaac-Reach-Dual-PSM-IK-Rel-v0",
                "video": None,
                "mode": "live",
                "summary": "Control two PSM instruments and switch between them while maintaining a shared plan.",
                "goal": "Place both tools without crossing or losing sight of either instrument.",
                "concepts": ["bimanual control", "coordination", "state"],
            },
        ],
    },
    {
        "id": "learning-from-demonstration",
        "number": "02",
        "title": "Learning from demonstrations",
        "short_title": "Demonstrations",
        "description": "Show the robot a good example, save every action, and understand how Behavior Cloning learns from it.",
        "lessons": [
            {
                "id": "needle-lift",
                "title": "Needle lift",
                "eyebrow": "Runnable lab + SuFIA-BC reference · 20 min",
                "task": "Isaac-Lift-Needle-PSM-IK-Rel-v0",
                "procedure_id": "needle-pickup",
                "video": "/research/videos/lift.mp4",
                "mode": "live",
                "summary": "Watch an expert lift, perform your own attempt, and save it as training data.",
                "goal": "Approach the curved needle, close the gripper, and lift without losing the grasp.",
                "concepts": ["demonstration", "Behavior Cloning", "trajectory"],
            },
            {
                "id": "needle-handover",
                "title": "Needle handover",
                "eyebrow": "Runnable bimanual lab + SuFIA-BC reference · 25 min",
                "task": "Isaac-Handover-Needle-Dual-PSM-IK-Rel-v0",
                "procedure_id": "needle-transfer",
                "video": "/research/videos/handover.mp4",
                "mode": "live",
                "summary": "Pass a curved needle between instruments while preserving a usable grasp.",
                "goal": "The receiving gripper secures the needle before the first instrument releases it.",
                "concepts": ["handover", "timing", "multi-arm policy"],
            },
            {
                "id": "block-transfer",
                "title": "Block transfer",
                "eyebrow": "Runnable approximation + SuFIA-BC reference · 20 min",
                "task": "Isaac-Handover-Block-Dual-PSM-IK-Rel-v0",
                "video": "/research/videos/transfer.mp4",
                "mode": "live",
                "summary": "Use the rigid block handover environment to practise the coordination pattern shown in the research task.",
                "goal": "Transfer the object cleanly and compare your motion with the research reference.",
                "concepts": ["generalization", "object state", "demonstration quality"],
            },
        ],
    },
    {
        "id": "reinforcement-learning",
        "number": "03",
        "title": "Reinforcement learning",
        "short_title": "RL policies",
        "description": "Let a policy practise in simulation and improve from a score, like coaching by outcomes instead of copying motions.",
        "lessons": [
            {
                "id": "rl-reach",
                "title": "Train a reaching policy",
                "eyebrow": "Runnable training lab · 30+ min",
                "task": "Isaac-Reach-PSM-IK-Rel-v0",
                "training_task": "Isaac-Reach-PSM-v0",
                "video": None,
                "mode": "train",
                "summary": "Create a small RL run where the policy earns a better score by reaching the target accurately.",
                "goal": "Understand observation, action, reward, episode, and checkpoint from one bounded run.",
                "concepts": ["reward", "episode", "checkpoint"],
            },
            {
                "id": "rl-needle-lift",
                "title": "Train needle lifting",
                "eyebrow": "Runnable training lab · advanced",
                "task": "Isaac-Lift-Needle-PSM-IK-Rel-v0",
                "training_task": "Isaac-Lift-Needle-PSM-v0",
                "video": "/research/videos/lift.mp4",
                "mode": "train",
                "summary": "Compare outcome-driven RL with copying expert needle-lift demonstrations.",
                "goal": "Identify which parts of a delicate grasp are easiest to specify as a score and which are easier to demonstrate.",
                "concepts": ["reward design", "sample efficiency", "policy"],
            },
        ],
    },
    {
        "id": "visual-policy-lab",
        "number": "04",
        "title": "Visual policy lab",
        "short_title": "Vision",
        "description": "Explore why camera placement and 3D representation change what a surgical policy can learn.",
        "lessons": [
            {
                "id": "camera-view-generalization",
                "title": "Same task, different camera",
                "eyebrow": "SuFIA-BC supplementary study · 15 min",
                "task": None,
                "video": "/research/videos/Lift_view_train.mp4",
                "video_set": [
                    {"label": "Training view", "src": "/research/videos/Lift_view_train.mp4"},
                    {"label": "New view 1", "src": "/research/videos/Lift_view_1.mp4"},
                    {"label": "New view 2", "src": "/research/videos/Lift_view_2.mp4"},
                ],
                "mode": "reference",
                "summary": "Compare the same needle-lift behavior from three viewpoints and see why a 2D image policy can be viewpoint-sensitive.",
                "goal": "Explain which visual clues remain stable when the camera moves.",
                "concepts": ["multi-view", "robustness", "visual observation"],
            },
            {
                "id": "point-cloud-policy",
                "title": "From pixels to a 3D point cloud",
                "eyebrow": "SuFIA-BC 3D policy lesson · 15 min",
                "task": None,
                "video": "/research/videos/Tissue_view_train.mp4",
                "mode": "reference",
                "summary": "A color image says what each pixel looks like; depth adds how far away it is. Together they form a 3D point cloud.",
                "goal": "Compare a multi-camera image policy with a 3D Diffusion Policy built from one endoscopic RGB-D view.",
                "concepts": ["RGB-D", "point cloud", "Diffusion Policy"],
            },
            {
                "id": "needle-generalization",
                "title": "Generalize to a new needle",
                "eyebrow": "SuFIA-BC supplementary study · 12 min",
                "task": None,
                "video": "/research/videos/needle_n1.mp4",
                "video_set": [
                    {"label": f"Needle {index}", "src": f"/research/videos/needle_n{index}.mp4"}
                    for index in range(1, 6)
                ],
                "mode": "reference",
                "summary": "Compare five needle instances to understand object generalization rather than memorizing one exact shape.",
                "goal": "Spot what the policy must treat as essential: graspable geometry, pose, and curvature.",
                "concepts": ["instance generalization", "domain variation", "robust policy"],
            },
        ],
    },
    {
        "id": "procedure-studies",
        "number": "05",
        "title": "Procedure studies",
        "short_title": "Procedures",
        "description": "Break research procedures into observable phases before building a safe supervised-autonomy task.",
        "lessons": [
            {
                "id": "shunt-insertion",
                "title": "Shunt insertion",
                "eyebrow": "Runnable ORBIT-style procedure lab · 25 min",
                "task": "Isaac-Lift-Block-PSM-IK-Rel-v0",
                "procedure_id": "vascular-shunt-insertion",
                "video": None,
                "mode": "live",
                "summary": "Acquire a flexible shunt, align it with the vessel lumen, advance while monitoring wall load, and verify simulated patency.",
                "goal": "Reach the planned depth without buckling or excessive wall-load proxy, then hold a stable verification pose.",
                "concepts": ["flexible insertion", "lumen alignment", "patency proxy", "human hand-back"],
                "truth_note": "Dr.Anmar now supplies a runnable engineering implementation of the paper benchmark. The flexible tube, wall-load and patency models are not clinically calibrated.",
            },
            {
                "id": "tissue-retraction",
                "title": "Tissue retraction",
                "eyebrow": "SuFIA-BC research reference · organ scene",
                "task": "Isaac-Lift-Block-PSM-IK-Rel-v0",
                "procedure_id": "liver-retraction",
                "video": "/research/videos/tissue.mp4",
                "mode": "live",
                "summary": "Observe how a visual policy grasps and retracts deformable tissue while preserving the operative view.",
                "goal": "Identify tissue state, safe grasp region, desired exposure, and release conditions.",
                "concepts": ["deformable tissue", "visual feedback", "safety boundary"],
            },
            {
                "id": "suture-pad",
                "title": "Suture pad interaction",
                "eyebrow": "SuFIA-BC research reference",
                "task": None,
                "video": "/research/videos/suture.mp4",
                "mode": "reference",
                "summary": "Study needle approach and contact around a suturing pad as an example of precise visual behavior.",
                "goal": "Separate the approach, contact, passage, and recovery phases.",
                "concepts": ["contact-rich task", "phase", "precision"],
            },
        ],
    },
]


COURSES.extend(
    [
        {
            "id": "suturing-reconstruction",
            "number": "06",
            "title": "Suturing and reconstruction",
            "short_title": "Suturing",
            "description": "Build the complete long-horizon skill chain from one tissue bite through knot security and pressure-tested anastomosis.",
            "lessons": [
                {
                    "id": "interrupted-stitch-live",
                    "title": "Single interrupted stitch",
                    "eyebrow": "Runnable tissue-and-thread lab · 25 min",
                    "task": "Isaac-Handover-Needle-Dual-PSM-IK-Rel-v0",
                    "procedure_id": "suture-threading-path",
                    "video": "/research/videos/suture.mp4",
                    "mode": "live",
                    "summary": "Drive one curved needle through tissue, pull the attached strand through, and secure the resulting loop.",
                    "goal": "Create a readable entry and exit, avoid excess tension, and finish with a stable cinch.",
                    "concepts": ["tissue bite", "thread tension", "knot constraint"],
                },
                {
                    "id": "running-suture-live",
                    "title": "Running suturing",
                    "eyebrow": "Runnable multi-bite lab · 35 min",
                    "task": "Isaac-Handover-Needle-Dual-PSM-IK-Rel-v0",
                    "procedure_id": "running-suture",
                    "video": None,
                    "mode": "live",
                    "summary": "Place three connected tissue bites while keeping spacing, closure gap and thread tension consistent.",
                    "goal": "Approximate the wound with evenly distributed bites and secure the final loop.",
                    "concepts": ["continuous closure", "bite spacing", "tension distribution"],
                },
                {
                    "id": "intracorporeal-knot-live",
                    "title": "Intracorporeal knot tying",
                    "eyebrow": "Runnable bimanual loop lab · 30 min",
                    "task": "Isaac-Handover-Needle-Dual-PSM-IK-Rel-v0",
                    "procedure_id": "intracorporeal-knot",
                    "video": None,
                    "mode": "live",
                    "summary": "Coordinate two instruments to form opposing throws and seat a stable square-knot proxy.",
                    "goal": "Alternate crossing direction, retain prior throws, and avoid excess tension.",
                    "concepts": ["loop topology", "opposing throws", "knot security"],
                },
                {
                    "id": "needle-hoop-threading-live",
                    "title": "Hoop pass and surgeon's knot",
                    "eyebrow": "Runnable bimanual dry-lab sequence · 25 min",
                    "task": "Isaac-Handover-Needle-Dual-PSM-IK-Rel-v0",
                    "procedure_id": "needle-hoop-threading",
                    "video": None,
                    "mode": "live",
                    "summary": "Control a threaded curved needle through the physical hoop, then form a double first throw followed by two opposing securing throws.",
                    "goal": "Complete a clean pass and seat a symmetric 2-1-1 surgeon's-knot sequence without strand slippage or excess tension.",
                    "concepts": ["hand-eye coordination", "thread control", "double first throw", "opposing throws", "knot security"],
                },
                {
                    "id": "needle-passing-regrasp-live",
                    "title": "Needle passing and regrasping",
                    "eyebrow": "Runnable bimanual orientation lab · 25 min",
                    "task": "Isaac-Handover-Needle-Dual-PSM-IK-Rel-v0",
                    "procedure_id": "needle-passing-regrasp",
                    "video": None,
                    "mode": "live",
                    "summary": "Pass a needle between instruments and deliberately rebuild a useful driving angle before the next bite.",
                    "goal": "Maintain custody, control the curved body, and finish in a repeatable needle-driving orientation.",
                    "concepts": ["needle orientation", "regrasp", "bimanual custody"],
                },
                {
                    "id": "anastomosis-live",
                    "title": "Anastomosis and leak test",
                    "eyebrow": "Runnable reconstruction challenge · 45 min",
                    "task": "Isaac-Handover-Needle-Dual-PSM-IK-Rel-v0",
                    "procedure_id": "anastomosis-leak-test",
                    "video": None,
                    "mode": "live",
                    "summary": "Approximate two lumen ends with distributed stitches and inspect a simulated pressure/leak response.",
                    "goal": "Close the lumen while preserving diameter and reducing the engineering leak-rate proxy.",
                    "concepts": ["anastomosis", "lumen narrowing", "pressure test"],
                },
            ],
        },
        {
            "id": "clinical-procedure-labs",
            "number": "07",
            "title": "Clinical procedure laboratories",
            "short_title": "Procedure labs",
            "description": "Combine access, vascular control, dissection, imaging and complication recovery in anatomy-aware rooms.",
            "lessons": [
                {
                    "id": "clip-divide-live",
                    "title": "Clip, ligate and divide",
                    "eyebrow": "Runnable vascular-control lab · 30 min",
                    "task": "Isaac-Reach-Dual-PSM-IK-Rel-v0",
                    "procedure_id": "vessel-clip-divide",
                    "video": None,
                    "mode": "live",
                    "summary": "Place two clips and divide only inside the protected interval.",
                    "goal": "Achieve simulated flow arrest while preserving clip spacing and protected clearance.",
                    "concepts": ["vascular control", "protected interval", "flow proxy"],
                },
                {
                    "id": "hemostasis-live",
                    "title": "Bleeding control",
                    "eyebrow": "Runnable complication lab · 30 min",
                    "task": "Isaac-Reach-Dual-PSM-IK-Rel-v0",
                    "procedure_id": "bleeding-control",
                    "video": None,
                    "mode": "live",
                    "summary": "Localize a dynamic bleed source and combine exposure, suction, compression and definitive control.",
                    "goal": "Reduce the simulated flow, preserve visibility, and observe for rebleed.",
                    "concepts": ["hemostasis", "visibility", "complication response"],
                },
                {
                    "id": "dissection-live",
                    "title": "Tissue-plane dissection",
                    "eyebrow": "Runnable topology-changing lab · 35 min",
                    "task": "Isaac-Reach-Dual-PSM-IK-Rel-v0",
                    "procedure_id": "tissue-plane-dissection",
                    "video": None,
                    "mode": "live",
                    "summary": "Use bimanual exposure and short controlled movements to separate an intended tissue plane.",
                    "goal": "Complete the plane while remaining outside protected duct and vessel corridors.",
                    "concepts": ["counter-traction", "dissection plane", "protected anatomy"],
                },
                {
                    "id": "ultrasound-access-live",
                    "title": "Ultrasound-guided access",
                    "eyebrow": "Runnable procedural B-mode lab · 30 min",
                    "task": "Isaac-Reach-Dual-PSM-IK-Rel-v0",
                    "procedure_id": "ultrasound-guided-access",
                    "video": None,
                    "mode": "live",
                    "summary": "Acquire a target, maintain in-plane needle visibility, and reach it while preserving vessel clearance.",
                    "goal": "Reach the target zone with high visibility and a safe protected-structure margin.",
                    "concepts": ["B-mode", "in-plane access", "target confidence"],
                },
                {
                    "id": "biopsy-live",
                    "title": "Biopsy and lesion excision",
                    "eyebrow": "Runnable topology-changing lab · 35 min",
                    "task": "Isaac-Reach-Dual-PSM-IK-Rel-v0",
                    "procedure_id": "biopsy-lesion-excision",
                    "video": None,
                    "mode": "live",
                    "summary": "Stabilize a lesion target, trace the planned margin, and release the specimen.",
                    "goal": "Create a consistent geometric margin while preserving the protected region.",
                    "concepts": ["margin planning", "excision", "specimen release"],
                },
                {
                    "id": "recovery-live",
                    "title": "Complication recovery",
                    "eyebrow": "Runnable randomized challenge · 25 min",
                    "task": "Isaac-Handover-Needle-Dual-PSM-IK-Rel-v0",
                    "procedure_id": "complication-recovery",
                    "video": None,
                    "mode": "live",
                    "summary": "Recognize a failure, stop unsafe movement, restore visibility, reacquire the object and hand back safely.",
                    "goal": "Demonstrate conservative recovery rather than continuing through uncertainty.",
                    "concepts": ["failure recognition", "recovery", "human hand-back"],
                },
            ],
        },
        {
            "id": "anatomy-manipulation-labs",
            "number": "08",
            "title": "Anatomy handling and access",
            "short_title": "Anatomy skills",
            "description": "Practise controlled incision, organ exposure, relocation and anatomy variation before combining them into longer procedures.",
            "lessons": [
                {
                    "id": "liver-incision-live",
                    "title": "Planned liver incision",
                    "eyebrow": "Runnable cutting-path lab · 25 min",
                    "task": "Isaac-Reach-PSM-IK-Rel-v0",
                    "procedure_id": "liver-cutting-path",
                    "video": None,
                    "mode": "live",
                    "summary": "Follow a planned surface line while observing incision length, topology revisions and protected clearance.",
                    "goal": "Complete the intended line with a continuous, economical tool path and no protected-zone entry.",
                    "concepts": ["incision planning", "topology change", "margin control"],
                },
                {
                    "id": "gallbladder-reposition-live",
                    "title": "Gallbladder repositioning",
                    "eyebrow": "Runnable compliant-organ lab · 20 min",
                    "task": "Isaac-Lift-Block-PSM-IK-Rel-v0",
                    "procedure_id": "gallbladder-reposition",
                    "video": None,
                    "mode": "live",
                    "summary": "Acquire a safe grasp region, reposition the organ and release it into a stable exposure pose.",
                    "goal": "Create useful exposure while minimizing displacement and peak surface load proxies.",
                    "concepts": ["atraumatic grasp", "organ exposure", "compliance"],
                },
                {
                    "id": "bladder-relocation-live",
                    "title": "Bimanual bladder-part relocation",
                    "eyebrow": "Runnable bimanual anatomy lab · 25 min",
                    "task": "Isaac-Handover-Block-Dual-PSM-IK-Rel-v0",
                    "procedure_id": "bladder-handover",
                    "video": None,
                    "mode": "live",
                    "summary": "Coordinate two instruments to relocate a compliant anatomy proxy without losing support or visibility.",
                    "goal": "Transfer support deliberately and settle the anatomy in the target region without a drop.",
                    "concepts": ["bimanual support", "organ relocation", "handover timing"],
                },
                {
                    "id": "anatomy-variation-live",
                    "title": "Navigate patient-shape variation",
                    "eyebrow": "Runnable MAISI/OpenUSD comparison · 20 min",
                    "task": "Isaac-Reach-PSM-IK-Rel-v0",
                    "procedure_id": "synthetic-anatomy-navigation",
                    "video": None,
                    "mode": "live",
                    "summary": "Repeat a controlled reach across the installed anatomy presets and compare how geometry changes the approach corridor.",
                    "goal": "Adapt the camera and approach plan rather than memorizing one scene geometry.",
                    "concepts": ["anatomy variation", "domain generalization", "approach planning"],
                },
            ],
        },
    ]
)


POLICY_GUIDE = [
    {
        "id": "behavior-cloning",
        "name": "Behavior Cloning",
        "analogy": "Like a resident copying many expert demonstrations.",
        "learns_from": "Recorded observation → action pairs",
        "strength": "Natural motions and fast learning when demonstrations are consistent",
        "watch_for": "It can struggle when it reaches a situation not represented in the examples",
    },
    {
        "id": "reinforcement-learning",
        "name": "Reinforcement Learning",
        "analogy": "Like practising repeatedly with a precise score after every attempt.",
        "learns_from": "Rewards, penalties, and simulated trial-and-error",
        "strength": "Can discover strategies beyond the demonstrations",
        "watch_for": "A poorly designed score can teach technically successful but clinically undesirable behavior",
    },
    {
        "id": "visual-bc",
        "name": "Visual Behavior Cloning",
        "analogy": "The resident sees the camera view and learns which motion usually follows.",
        "learns_from": "Images or point clouds paired with expert actions",
        "strength": "Uses the same kind of visual input available during endoscopic procedures",
        "watch_for": "Camera, lighting, anatomy, and instrument variation must be represented",
    },
]


GLOSSARY = [
    ("Action", "The command sent to the simulated robot, such as a small tool movement or gripper change."),
    ("Behavior Cloning", "Learning to imitate expert actions from recorded examples."),
    ("Checkpoint", "A saved version of a policy during training; like saving progress at a particular practice session."),
    ("Demonstration", "A time-aligned recording of what the robot observed and what the expert commanded."),
    ("Digital twin", "A simulation of the robot, instruments, objects, anatomy, cameras, and physics used for safe experiments."),
    ("Episode", "One practice attempt, from reset until success, failure, or timeout."),
    ("Observation", "The information available to the policy: robot state, camera images, depth, object pose, or a combination."),
    ("Policy", "The learned decision-maker that converts an observation into the next action."),
    ("Point cloud", "A 3D collection of points produced from color plus depth; each point represents a visible surface location."),
    ("Reward", "The numeric coaching signal used by reinforcement learning."),
    ("Synthetic data", "Training examples generated in simulation, where geometry, state, and camera labels are known exactly."),
    ("Supervised autonomy", "The robot performs a bounded behavior while a clinician monitors, can interrupt, and retains authority."),
]


def curriculum_payload() -> dict:
    lessons = [lesson for course in COURSES for lesson in course["lessons"]]
    return {
        "courses": COURSES,
        "policies": POLICY_GUIDE,
        "glossary": [{"term": term, "definition": definition} for term, definition in GLOSSARY],
        "lesson_count": len(lessons),
        "runnable_count": sum(lesson["mode"] in {"live", "train"} for lesson in lessons),
        "simulation_only": True,
        "sources": {
            "orbit": "https://orbit-surgical.github.io/",
            "orbit_paper": "https://autolab.berkeley.edu/assets/publications/media/2024-ICRA-ORBIT-Surgical.pdf",
            "sufia_bc": "https://orbit-surgical.github.io/sufia-bc/",
            "sufia_bc_paper": "https://autolab.berkeley.edu/assets/publications/media/sufia_bc.pdf",
        },
    }
